## ***Initials***

In [1]:
import pandas as pd
import json
from sklearn.preprocessing import MinMaxScaler
import random
import json

## ***Help Functions***

In [2]:
# function that: provides a justification for an individual feature, based on its comparison with the stats
def justify_feature(feature, value, stats):

    # extract the stats for the specific feature
    feature_stats = stats[feature]

    # ============ Neighborhood-level features ============

    # Neighborhood_Area_km2
    if feature == "Neighborhood_Area_km2":
        val_str = f"{value:.2f}"
        if value >= feature_stats["q75"]:
            return random.choice([
                f"a spacious neighborhood ({val_str} km²) with plenty of room to grow your business",
                f"an open area ({val_str} km²) that offers flexibility for setting up and expanding",
                f"a low-density location ({val_str} km²) that gives you more space and future options"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                f"a compact neighborhood ({val_str} km²) where your business could benefit from steady foot traffic",
                f"a smaller, denser area ({val_str} km²) that helps keep you close to potential customers",
                f"a cozy location ({val_str} km²) that might work well for storefronts or quick-service ideas"
            ])
        else:
            return random.choice([
                f"a moderately sized area ({val_str} km²) that balances space and accessibility",
                f"a neighborhood ({val_str} km²) that offers enough room without feeling too spread out",
                f"a balanced location ({val_str} km²) — not too dense, not too open"
            ])

    # distance_to_volos_center_km
    elif feature == "distance_to_volos_center_km":
        val_str = f"{value:.2f}"        
        if value <= feature_stats["q25"]:
            return random.choice([
                f"it's very close to the city center ({val_str} km), which means great visibility and easy access",
                f"you'll be right near the heart of Volos ({val_str} km) — convenient for both customers and deliveries",
                f"excellent central location ({val_str} km), making your business easy to find and reach"
            ])
        elif value >= feature_stats["q75"]:
            return random.choice([
                f"a quieter spot farther from the city center ({val_str} km) — ideal if you're looking for lower rents or a more relaxed vibe",
                f"located outside the busy core ({val_str} km), which could suit destination businesses or niche services",
                f"a more peaceful area ({val_str} km) that gives you space away from the hustle and bustle"
            ])
        else:
            return random.choice([
                f"a balanced location ({val_str} km) — not too far from the city center, but away from the busiest spots",
                f"close enough ({val_str} km) to be convenient, while still offering some breathing room from downtown traffic",
                f"a well-positioned area ({val_str} km) that gives you access without the rush of the city core"
            ])

    # distance_to_volos_port_km
    elif feature == "distance_to_volos_port_km":
        val_str = f"{value:.2f}"        
        if value <= feature_stats["q25"]:
            return random.choice([
                f"very close to the port ({val_str} km), which makes transport and logistics a lot easier",
                f"a great spot ({val_str} km from the port) if you rely on shipping or receiving goods through Volos port",
                f"conveniently located near the port ({val_str} km) — helpful for supply chains or frequent deliveries"
            ])
        elif value >= feature_stats["q75"]:
            return random.choice([
                f"a bit farther from the port ({val_str} km), which might suit businesses focused on local customers",
                f"not near the maritime hub ({val_str} km away), so it's more suited for neighborhood services than heavy logistics",
                f"further inland ({val_str} km) — great if you’re not dependent on port access or want a quieter setting"
            ])
        else:
            return random.choice([
                f"a reasonably accessible location ({val_str} km) — not right next to the port, but still within reach if needed",
                f"a balanced distance from the port ({val_str} km), offering some flexibility without relying heavily on shipping",
                f"not too far from the port ({val_str} km), so occasional logistics or deliveries should still be manageable"
            ])

    # dist_to_main_road_km
    elif feature == "dist_to_main_road_km":
        val_str = f"{value:.2f}"        
        if value <= feature_stats["q25"]:
            return random.choice([
                f"great access to main roads ({val_str} km) — easy for customers to reach you and for deliveries to run smoothly",
                f"close to major roads ({val_str} km), which is perfect if visibility and convenience matter for your business",
                f"well-connected by road ({val_str} km), making it easy to attract drive-by traffic or manage logistics"
            ])
        elif value >= feature_stats["q75"]:
            return random.choice([
                f"a bit off the main roads ({val_str} km) — could be a good fit for quieter, destination-style businesses",
                f"more tucked away from busy streets ({val_str} km), which might appeal if you’re looking for a calm setup",
                f"less direct road access ({val_str} km), but that can mean a more peaceful or residential setting"
            ])
        else:
            return random.choice([
                f"reasonably close to main roads ({val_str} km), giving you decent accessibility without heavy traffic",
                f"a balanced spot ({val_str} km) — not right on a major road, but still convenient for customers and deliveries",
                f"accessible without being too exposed to street noise or congestion ({val_str} km)"
            ])

    # dist_to_bus_stop_km
    elif feature == "dist_to_bus_stop_km":
        val_str = f"{value:.2f}"        
        if value <= feature_stats["q25"]:
            return random.choice([
                f"really close to a bus stop ({val_str} km) — super convenient for customers who rely on public transport",
                f"excellent access to public transit ({val_str} km), which can boost foot traffic to your business",
                f"a well-connected spot ({val_str} km from a bus stop) that’s easy for people to reach without a car"
            ])
        elif value >= feature_stats["q75"]:
            return random.choice([
                f"a bit further from bus stops ({val_str} km), so it may work better for businesses that don’t rely on walk-ins",
                f"less accessible by public transport ({val_str} km) — ideal if your customers tend to drive or book in advance",
                f"not as transit-friendly ({val_str} km from the nearest stop), but that can suit more niche or appointment-based services"
            ])
        else:
            return random.choice([
                f"fairly accessible by public transport ({val_str} km), even if not right next to a bus stop",
                f"a reasonable distance from transit ({val_str} km) — close enough for most customers to reach you without much hassle",
                f"not far from a bus stop ({val_str} km), offering a decent balance between foot traffic and privacy"
            ])

    # dist_to_university_km
    elif feature == "dist_to_university_km":
        val_str = f"{value:.2f}"        
        if value <= feature_stats["q25"]:
            return random.choice([
                f"right near the university ({val_str} km) — great if you want to attract students or young professionals",
                f"close to campus ({val_str} km), which means steady foot traffic from a younger, educated crowd",
                f"a lively spot near the university ({val_str} km) that could bring in a lot of student activity"
            ])
        elif value >= feature_stats["q75"]:
            return random.choice([
                f"farther from the university ({val_str} km), so you’ll likely attract more local or residential customers",
                f"not close to campus ({val_str} km), which could work well for businesses focused on the neighborhood itself",
                f"a quieter area away from student zones ({val_str} km) — great if your business serves families or older residents"
            ])
        else:
            return random.choice([
                f"not far from the university ({val_str} km), which gives you access to both student and local customer bases",
                f"a nicely balanced location ({val_str} km) — close enough to feel the university’s presence, but not reliant on it",
                f"within reasonable distance from campus ({val_str} km), allowing you to serve a mix of demographics"
            ])


    # ============ Municipal-community-level features ============

    # Population (we dont use actual numbers because the number refers to the municipal community!)
    elif feature == "Population":
        if value >= feature_stats["q75"]:
            return random.choice([
                "a large local population, which can bring in steady foot traffic",
                "lots of people live in the area — great for attracting walk-in customers",
                "a busy neighborhood with a strong base of potential customers nearby"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                "a smaller local population — might work well for niche or low-competition businesses",
                "not a crowded area, which could be ideal if you're targeting a specific community or want less competition",
                "a quieter neighborhood — potentially great for destination-style or appointment-based services"
            ])
        else:
            return random.choice([
                "a moderately populated area — offering a steady customer base without feeling overcrowded",
                "enough local residents to support a variety of businesses, while still feeling manageable",
                "a balanced population size that gives you both reach and room to grow"
            ])

    # Άγαμοι_pct
    elif feature == "Άγαμοι_pct":
        val_str = f"{value * 100:.0f}%"
        if value >= feature_stats["q75"]:
            return random.choice([
                f"a high percentage of single residents ({val_str}) — a good fit for trendy, flexible, or lifestyle-focused services",
                f"lots of singles in the area ({val_str}), which might favor casual dining, entertainment, or solo-friendly businesses",
                f"a neighborhood with many single adults ({val_str}) — ideal for modern, fast-moving business models"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                f"a lower proportion of singles ({val_str}), which might suggest more family-oriented or community-focused needs",
                f"not many singles in the area ({val_str}) — may be better suited for services geared toward couples or families",
                f"a family-heavy area ({val_str}) where traditional or home-focused businesses might do well"
            ])
        else:
            return random.choice([
                f"a mix of single and married residents ({val_str}), offering flexibility for a variety of business types",
                f"a balanced demographic ({val_str}) — your business could appeal to both individuals and families",
                f"a good blend of household types ({val_str}), making it easier to tailor your services to different lifestyles"
            ])

    # Έγγαμοι_pct
    elif feature == "Έγγαμοι_pct":
        val_str = f"{value * 100:.0f}%"
        if value >= feature_stats["q75"]:
            return random.choice([
                f"a strong family presence ({val_str}) — great for businesses that serve households or children",
                f"many married residents ({val_str}), which could support family-friendly services and stable customer bases",
                f"a family-oriented community ({val_str}), ideal for shops, education services, or everyday essentials"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                f"fewer married residents ({val_str}), which could favor services tailored to individuals or younger adults",
                f"a more independent population ({val_str}) — potentially a good match for flexible or solo-oriented offerings",
                f"not a highly family-focused area ({val_str}), which may suit lifestyle or trend-based businesses"
            ])
        else:
            return random.choice([
                f"a mix of married and unmarried residents ({val_str}), giving you room to serve both families and individuals",
                f"a well-balanced demographic ({val_str}) — suitable for businesses with broad appeal",
                f"a neighborhood with diverse household types ({val_str}), so you can adapt to different customer needs"
            ])

    # Χήροι_pct
    elif feature == "Χήροι_pct":
        val_str = f"{value * 100:.0f}%"
        if value >= feature_stats["q75"]:
            return random.choice([
                f"a significant elderly population ({val_str}), which may increase demand for age-friendly or supportive services",
                f"many widowed residents in the area ({val_str}) — a good fit for healthcare, wellness, or social support businesses",
                f"an older community ({val_str}) that may appreciate thoughtful, accessible, or community-based offerings"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                f"fewer widowed residents ({val_str}), likely indicating a younger or more middle-aged community",
                f"a relatively young population ({val_str}) — may be better suited for active lifestyle or trend-oriented services",
                f"not a heavily elderly area ({val_str}), which could favor modern, fast-paced, or tech-forward businesses"
            ])
        else:
            return random.choice([
                f"a balanced age distribution ({val_str}), allowing flexibility in the type of services you offer",
                f"a mix of age groups ({val_str}) — giving you room to appeal to both older and younger customers",
                f"a moderately aged population ({val_str}) that supports a variety of business models"
            ])

    # Διαζευγμένοι_pct
    elif feature == "Διαζευγμένοι_pct":
        val_str = f"{value * 100:.0f}%"
        if value >= feature_stats["q75"]:
            return random.choice([
                f"a higher percentage of divorced residents ({val_str}) — often linked to urban lifestyles and more independent living",
                f"a socially dynamic area ({val_str}), which might favor flexible or lifestyle-oriented businesses",
                f"a neighborhood with many single-adult households ({val_str}) — ideal for personal services or solo-focused offerings"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                f"a lower percentage of divorced individuals ({val_str}), possibly indicating a more traditional or family-centered community",
                f"fewer divorced residents ({val_str}) — may suggest stronger household stability and family-oriented needs",
                f"a close-knit area with fewer single-adult households ({val_str}), which could suit more community- or family-focused services"
            ])
        else:
            return random.choice([
                f"a balanced mix of relationship statuses ({val_str}) — allowing room for a wide range of services",
                f"a varied community structure ({val_str}), making it easy to adapt to different customer lifestyles",
                f"no strong leaning in household types ({val_str}), giving you flexibility in how you position your business"
            ])

    # age_0_14_pct
    elif feature == "age_0_14_pct":
        val_str = f"{value * 100:.0f}%"
        if value >= feature_stats["q75"]:
            return random.choice([
                f"a young population base ({val_str}) — ideal for child-focused products, services, or education offerings",
                f"many families with children in the area ({val_str}), which is great for schools, toys, or family-friendly businesses",
                f"a kid-friendly neighborhood ({val_str}) where child-oriented businesses could thrive"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                f"fewer children in the area ({val_str}) — may be better suited for adult-focused or specialized services",
                f"not a particularly family-heavy area ({val_str}), which could work well for quiet or professional businesses",
                f"a smaller child population ({val_str}), likely indicating a more adult or older resident base"
            ])
        else:
            return random.choice([
                f"a balanced age mix ({val_str}) that allows flexibility in serving both families and individuals",
                f"a community with some children ({val_str}), but not overly youth-oriented — good for general-purpose services",
                f"a moderate presence of young residents ({val_str}), giving you a bit of reach into family needs without being limiting"
            ])

    # age_15_64_pct
    elif feature == "age_15_64_pct":
        val_str = f"{value * 100:.0f}%"
        if value >= feature_stats["q75"]:
            return random.choice([
                f"a dominant working-age population ({val_str}) — great for everyday services, retail, or food businesses",
                f"lots of working-age residents in the area ({val_str}), which supports demand for convenience and lifestyle offerings",
                f"a strong base of economically active people ({val_str}) — ideal for practical, fast-paced, or high-demand services"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                f"fewer working-age adults ({val_str}) — could be better suited for services focused on families, retirees, or youth",
                f"not a highly active working-age population ({val_str}), so businesses may lean toward community or care-oriented needs",
                f"a quieter demographic in terms of workforce ({val_str}) — may suit slower-paced or relationship-driven services"
            ])
        else:
            return random.choice([
                f"a balanced population with a good share of working-age adults ({val_str}), offering versatility in business types",
                f"a healthy mix of age groups ({val_str}), so your services can appeal to both professionals and families",
                f"a solid working-age base ({val_str}), without being too concentrated — gives you some flexibility"
            ])

    # age_65_plus_pct
    elif feature == "age_65_plus_pct":
        val_str = f"{value * 100:.0f}%"
        if value >= feature_stats["q75"]:
            return random.choice([
                f"a large elderly population ({val_str}) — ideal for healthcare, wellness, or senior-friendly services",
                f"many older residents in the area ({val_str}), which may benefit businesses focused on comfort, care, or community",
                f"a senior-friendly neighborhood ({val_str}) where age-conscious services could really stand out"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                f"fewer elderly residents ({val_str}) — likely a more active or younger community, great for trend-driven services",
                f"not a senior-heavy area ({val_str}), which may suit businesses targeting professionals or families",
                f"a younger demographic overall ({val_str}), opening up space for dynamic or tech-forward offerings"
            ])
        else:
            return random.choice([
                f"a balanced age distribution ({val_str}), giving you the flexibility to serve both older and younger customers",
                f"a moderate number of older residents ({val_str}) — enough to consider including age-friendly features in your business",
                f"a diverse age mix ({val_str}) that allows you to tailor your offerings more broadly"
            ])

    # low_education_pct
    elif feature == "low_education_pct":
        val_str = f"{value * 100:.0f}%"
        if value >= feature_stats["q75"]:
            return random.choice([
                f"a community with fewer formal education credentials ({val_str}) — vocational or practical services may resonate well here",
                f"many residents without advanced education ({val_str}), so accessible, easy-to-use services might perform better",
                f"an area where clear, approachable offerings ({val_str}) could stand out and serve real needs"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                f"a highly educated population ({val_str}) — businesses that involve technology, consulting, or specialized services may thrive",
                f"very few residents with low education levels ({val_str}), which may favor knowledge-based or premium offerings",
                f"an area where education levels are high ({val_str}), often a good match for professional or creative services"
            ])
        else:
            return random.choice([
                f"a balanced mix of education levels ({val_str}) — offering flexibility in how you position your business",
                f"a diverse community in terms of education ({val_str}), giving you room to tailor your services broadly",
                f"a moderate education profile ({val_str}) that allows for both entry-level and specialized offerings"
            ])

    # medium_education_pct
    elif feature == "medium_education_pct":
        val_str = f"{value * 100:.0f}%"
        if value >= feature_stats["q75"]:
            return random.choice([
                f"a largely middle-educated community ({val_str}) — versatile enough to support a wide range of everyday services",
                f"many residents with secondary-level education ({val_str}), making this a good fit for accessible and practical offerings",
                f"a solid foundation of education in the area ({val_str}), ideal for general-purpose businesses and services"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                f"fewer residents with middle-level education ({val_str}) — consider offerings that are either highly specialized or more entry-level",
                f"not a strong presence of middle-educated residents ({val_str}), so focusing on either basic or high-skill services may work better",
                f"an unusual education profile ({val_str}) — tailoring your business to either high-end or highly accessible services could stand out"
            ])
        else:
            return random.choice([
                f"a balanced mix of education levels ({val_str}) — giving you flexibility to appeal to different customer types",
                f"a diverse educational profile ({val_str}), which opens up room for both everyday and more specialized services",
                f"a moderate level of education across the community ({val_str}) — suitable for broad business categories"
            ])

    # high_education_pct
    elif feature == "high_education_pct":
        val_str = f"{value * 100:.0f}%"
        if value >= feature_stats["q75"]:
            return random.choice([
                f"a highly educated community ({val_str}) — great for offering professional, tech, or consulting services",
                f"many residents with advanced degrees ({val_str}), which may support premium or specialized offerings",
                f"a well-educated area ({val_str}) that’s a good fit for knowledge-based or creative businesses"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                f"fewer highly educated residents ({val_str}) — practical, hands-on, or accessible services may work best here",
                f"a less academic demographic ({val_str}), where clear, simple offerings could resonate more strongly",
                f"not a highly educated area ({val_str}), which may favor vocational, day-to-day, or experience-based services"
            ])
        else:
            return random.choice([
                f"a moderately educated population ({val_str}) — flexible enough to support a range of business types",
                f"a balanced education level in the community ({val_str}), ideal for mixed-use or general-purpose services",
                f"a solid educational background overall ({val_str}), giving you freedom in how you position your business"
            ])

    # unemployment_rate
    elif feature == "unemployment_rate":
        val_str = f"{value * 100:.0f}%"
        if value <= feature_stats["q25"]:
            return random.choice([
                f"a low unemployment rate ({val_str}), which usually reflects economic stability and strong local spending power",
                f"a stable job market ({val_str}) — great for businesses that rely on consistent customer demand",
                f"very few people unemployed in the area ({val_str}), which can be a sign of overall economic health"
            ])
        elif value >= feature_stats["q75"]:
            return random.choice([
                f"a higher unemployment rate ({val_str}) — which may mean more available labor for hiring",
                f"many residents looking for work ({val_str}), which can be an opportunity if your business needs local staff",
                f"a softer job market ({val_str}) that could help you attract talent or offer affordable services"
            ])
        else:
            return random.choice([
                f"an average unemployment rate ({val_str}) — a stable environment for most types of businesses",
                f"a balanced labor market ({val_str}), providing both workforce availability and spending potential",
                f"employment levels are typical for the region ({val_str}), giving you flexibility in how you plan your business"
            ])

    # labor_force_participation_rate
    elif feature == "labor_force_participation_rate":
        val_str = f"{value * 100:.0f}%"
        if value >= feature_stats["q75"]:
            return random.choice([
                f"a highly active labor market ({val_str}) — great if you’re planning to hire locally or rely on working-age customers",
                f"many people are engaged in the workforce ({val_str}), which supports strong business operations",
                f"an economically active area ({val_str}) with good potential for both staffing and steady demand"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                f"a lower participation in the labor market ({val_str}) — businesses may want to focus on essential or community-oriented services",
                f"fewer people are actively working ({val_str}), which might favor businesses with low staffing needs or specialized demand",
                f"a quieter labor market ({val_str}) — potentially better for services that don’t rely on heavy footfall or large teams"
            ])
        else:
            return random.choice([
                f"a moderately engaged workforce ({val_str}), offering a stable environment for most types of businesses",
                f"a balanced labor force ({val_str}) — enough economic activity to support general services and hiring",
                f"a solid participation rate ({val_str}), giving you access to both workers and customers"
            ])

    # primary_sector_pct
    elif feature == "primary_sector_pct":
        val_str = f"{value * 100:.0f}%"
        if value >= feature_stats["q75"]:
            return random.choice([
                f"a community with strong roots in agriculture or natural resources ({val_str}) — great if you're offering services that support rural or farming needs",
                f"a high share of primary-sector activity ({val_str}), which could suit businesses tied to food production, tools, or local logistics",
                f"an area where agriculture and related trades are important ({val_str}) — useful to consider if you're aligned with those industries"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                f"limited activity in the primary sector ({val_str}) — better suited for urban-style or modern services",
                f"not strongly tied to agriculture ({val_str}), which opens the door for retail, tech, or lifestyle businesses",
                f"a more urbanized economy ({val_str}), favoring general consumer or service-based businesses"
            ])
        else:
            return random.choice([
                f"some involvement in the primary sector ({val_str}) — offering flexibility depending on your business type",
                f"a moderate presence of agriculture and similar industries ({val_str}), giving you room to tailor your services accordingly",
                f"a balanced economy ({val_str}) with partial ties to rural or resource-based activity"
            ])

    # secondary_sector_pct
    elif feature == "secondary_sector_pct":
        val_str = f"{value * 100:.0f}%"
        if value >= feature_stats["q75"]:
            return random.choice([
                f"a strong industrial or manufacturing presence ({val_str}) — useful if you're offering services to workers or B2B solutions",
                f"many residents work in industry ({val_str}), which may support logistics, equipment, or lunch-focused services",
                f"a manufacturing-heavy area ({val_str}), ideal for businesses that serve industrial hubs or production needs"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                f"minimal industrial activity ({val_str}) — likely a better fit for service-based, retail, or lifestyle businesses",
                f"not much manufacturing here ({val_str}), so service-oriented businesses may perform best",
                f"a light industrial presence ({val_str}), which favors customer-facing or creative offerings"
            ])
        else:
            return random.choice([
                f"a balanced mix of industrial and non-industrial jobs ({val_str}) — giving you room to adapt your offerings",
                f"some industrial activity in the area ({val_str}), but also space for service or retail businesses to thrive",
                f"a moderate industrial footprint ({val_str}) that lets you cater to a variety of working populations"
            ])

    # tertiary_sector_pct
    elif feature == "tertiary_sector_pct":
        val_str = f"{value * 100:.0f}%"
        if value >= feature_stats["q75"]:
            return random.choice([
                f"a strong service-sector economy ({val_str}) — great for launching customer-facing or professional businesses",
                f"many locals work in services ({val_str}), making this area well-suited for retail, health, education, or entertainment",
                f"a service-driven community ({val_str}), perfect for modern, experience-based, or consulting businesses"
            ])
        elif value <= feature_stats["q25"]:
            return random.choice([
                f"less focus on services ({val_str}) — this might be better suited for specialized, industrial, or local utility businesses",
                f"a lower share of service-sector jobs ({val_str}), so you may want to explore niche or B2B opportunities",
                f"not a highly service-oriented area ({val_str}), but that could be an opening for new commercial ideas"
            ])
        else:
            return random.choice([
                f"a reasonably service-oriented economy ({val_str}) — offering flexibility in the kinds of businesses that can thrive",
                f"a balanced employment profile ({val_str}) with solid opportunities for both service and support-focused ventures",
                f"an area with decent service activity ({val_str}), giving you room to tailor your offerings to local demand"
            ])

    # SKIP since we have the area of the neighborhood!
    ## Area_km2  
    # elif feature == "Area_km2":
    #     if value >= feature_stats["q75"]:
    #         return random.choice([
    #             "a large municipal area — offering space for development and attracting a diverse range of residents",
    #             "a wide geographic area, which could support future expansion or draw in customers from different zones",
    #             "plenty of room within the community boundaries, great for businesses that benefit from scale or variety"
    #         ])
    #     elif value <= feature_stats["q25"]:
    #         return random.choice([
    #             "a compact municipal area — likely with a denser customer base and easier local access",
    #             "a smaller community footprint, which may help build close customer relationships and brand presence",
    #             "a tight-knit area where businesses can thrive on local loyalty and word-of-mouth"
    #         ])
    #     else:
    #         return random.choice([
    #             "a moderately sized community — offering a good balance between reach and manageability",
    #             "enough area to support a mix of business types without feeling too spread out",
    #             "a balanced municipal size that allows for both local convenience and some growth opportunities"
    #         ])

    return None

In [3]:
# function that: creates an individual justification per feature of the neighborhood, and combines them 
# this time, we do not samle 4/7 fixed features, but we use all of them
# also, we do not use the feature importances for thr secondary features, 
def justify_neighborhood(neighborhood, neighborhood_stats, municipal_community_stats, neighborhood_colls, municipal_community_colls, all_features, fixed_features, max_reasons=5):
    
    individual_justifications = []
    used_features = set()


    # ================== Step 1: Justify fixed features ==================
    for feature in fixed_features:
        
        # Extract the stats of this feature
        if feature in neighborhood_colls:
            feature_stats = neighborhood_stats
        elif feature in municipal_community_colls:
            feature_stats = municipal_community_stats

        # Get the specific (FIXED) feature justification and add it to the total neighborhood justification
        feature_justification = justify_feature(feature, all_features[feature], feature_stats)
        if feature_justification:
            individual_justifications.append(feature_justification)
            used_features.add(feature)
        if len(individual_justifications) >= max_reasons:
            return f"{neighborhood} – {', '.join(individual_justifications)}."


    #  ================== Step 2: Add extra features (skipping any already used) ==================
    for feature in all_features:

        # Skip if the feature is not valid
        if feature in used_features:
            continue

        # Extract the stats of this feature
        if feature in neighborhood_colls:
            feature_stats = neighborhood_stats
        elif feature in municipal_community_colls:
            feature_stats = municipal_community_stats

        # Get the specific (EXTRA) feature justification and add it to the total neighborhood justification
        feature_justification = justify_feature(feature, all_features[feature], feature_stats)
        if feature_justification:
            individual_justifications.append(feature_justification)
            used_features.add(feature)
        if len(individual_justifications) >= max_reasons:
            break
    

    if not individual_justifications:
        return f"{neighborhood} – no significant distinguishing features found."
    return f"{neighborhood} – {', '.join(individual_justifications)}."

In [4]:
# function that: returns stats for all the features, so each feature can later be compared later
def compute_features_stats(df, features):
    stats = {}
    for feature in features:
        stats[feature] = {
            "mean": df[feature].mean(),
            "q25": df[feature].quantile(0.25),
            "q50": df[feature].quantile(0.50),
            "q75": df[feature].quantile(0.75),
        }
    return stats

In [5]:
# function that: returns the recommended features of a Neighborhood
def extract_neighborhood_features(neighborhood_name, neighborhood_ELSTAT_df, feature_cols):

    # find the 
    match1 = neighborhood_ELSTAT_df[neighborhood_ELSTAT_df['Neighborhood'] == neighborhood_name]
    if match1.empty:
        print(f"[WARNING] Neighborhood '{neighborhood_name}' not found in enriched dataset.")
        features = {}
    else:
        features = match1.iloc[0][feature_cols].to_dict()

    return features

## ***Load the Data***

### ***Neighborhoods***

In [6]:
neighborhood_df = pd.read_csv('C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\3. Base Datasets\\3. Data -  Smaller Spatial Units\\1. Neighborhoods\\Extracted CSV Files\\neighborhoods_enriched.csv')
neighborhood_df.drop(columns=['Neighborhood_Greek'], inplace=True)
print(neighborhood_df.shape)
print(neighborhood_df.columns)
neighborhood_df.head()

(48, 11)
Index(['Municipal Community', 'Neighborhood', 'Centroid_x', 'Centroid_y',
       'Neighborhood_Area_km2', 'Geometry', 'distance_to_volos_center_km',
       'distance_to_volos_port_km', 'dist_to_main_road_km',
       'dist_to_bus_stop_km', 'dist_to_university_km'],
      dtype='object')

,Municipal Community,Neighborhood,Centroid_x,Centroid_y,Neighborhood_Area_km2,Geometry,distance_to_volos_center_km,distance_to_volos_port_km,dist_to_main_road_km,dist_to_bus_stop_km,dist_to_university_km
0,Municipal Community of Dimini,Dimini,22.882945,39.349112,37.344776,MULTIPOLYGON (((406692.718139543 4357521.85294...,6.154015,5.418577,0.443434,1.569912,4.273031
1,Municipal Community of Sesklos,Xrisi Akti Panagias,22.836899,39.305430,9.983032,MULTIPOLYGON (((396744.165394512 4351195.65810...,11.932475,11.015584,2.299921,2.410375,10.100771
2,Municipal Community of Sesklos,Sesklo,22.838168,39.353051,27.367312,MULTIPOLYGON (((400839.361742302 4353031.79092...,9.814666,9.191001,0.482308,4.965561,7.989610
3,Municipal Community of Volos,Agioi Anargiroi,22.924059,39.366937,0.774436,MULTIPOLYGON (((406589.250339913 4357224.83344...,2.296184,1.978856,0.058142,0.063879,0.866021
4,Municipal Community of Volos,Aivaliotika,22.922660,39.343696,4.848904,MULTIPOLYGON (((407619.510540358 4356306.42684...,3.508166,2.529372,0.224486,0.246542,1.913456

### ***Municipal Communities***

In [7]:
municipal_community_df = pd.read_csv("C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\3. Base Datasets\\2. Data - Municipal Communities\\4. Exploratory Data Analysis\\Extracted CSV Files\\ELSTAT-demographic-economic.csv", index_col=0)
municipal_community_df.drop(columns=['ΔΗΜΟΤΙΚΗ ΚΟΙΝΟΤΗΤΑ ΕΛΛ'], inplace=True)
print(municipal_community_df.shape)
print(municipal_community_df.columns)
municipal_community_df.head()

(76, 21)
Index(['ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ', 'ΔΗΜΟΣ', 'ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ',
       'ΔΗΜΟΤΙΚΗ ΚΟΙΝΟΤΗΤΑ', 'Population', 'Άγαμοι_pct', 'Έγγαμοι_pct',
       'Χήροι_pct', 'Διαζευγμένοι_pct', 'age_0_14_pct', 'age_15_64_pct',
       'age_65_plus_pct', 'low_education_pct', 'medium_education_pct',
       'high_education_pct', 'unemployment_rate',
       'labor_force_participation_rate', 'primary_sector_pct',
       'secondary_sector_pct', 'tertiary_sector_pct', 'Area_km2'],
      dtype='object')

,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ,ΔΗΜΟΣ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ,ΔΗΜΟΤΙΚΗ ΚΟΙΝΟΤΗΤΑ,Population,Άγαμοι_pct,Έγγαμοι_pct,Χήροι_pct,Διαζευγμένοι_pct,age_0_14_pct,...,age_65_plus_pct,low_education_pct,medium_education_pct,high_education_pct,unemployment_rate,labor_force_participation_rate,primary_sector_pct,secondary_sector_pct,tertiary_sector_pct,Area_km2
0,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΒΟΛΟΥ,Municipal Community of Volos,85806,0.4032,0.4630,0.0809,0.0528,0.1300,...,0.2221,0.3634,0.3663,0.2704,0.1545,0.4188,0.0313,0.1666,0.8022,26.790807
1,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΓΡΙΑΣ,Municipal Community of Agria,4926,0.3577,0.5173,0.0796,0.0461,0.1407,...,0.2359,0.4670,0.3341,0.1987,0.1555,0.3955,0.0816,0.1864,0.7314,3.737347
2,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΓΡΙΑΣ,Municipal Community of Drakeia,369,0.3496,0.4580,0.1382,0.0325,0.1274,...,0.2873,0.6667,0.2493,0.0840,0.1439,0.3767,0.4545,0.0826,0.4628,21.683415
3,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΙΣΩΝΙΑΣ,Municipal Community of Dimini,2101,0.3889,0.5007,0.0776,0.0343,0.1480,...,0.2080,0.5437,0.3163,0.1395,0.2211,0.4327,0.1161,0.2365,0.6459,37.323451
4,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΙΣΩΝΙΑΣ,Municipal Community of Sesklos,899,0.3960,0.5184,0.0645,0.0234,0.1769,...,0.2147,0.6009,0.2812,0.1179,0.1304,0.3838,0.1424,0.3609,0.4967,37.329725

### ***Merged Neighborhoods with Municipal Communties***

In [8]:
neighborhood_ELSTAT_df = pd.read_csv("C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\4. Joining Datasets\\4. Joining Neighborhood - Municipal Community Data\\Extracted CSV Files\\neighborhood_ELSTAT.csv", index_col=0)

In [9]:
print(neighborhood_ELSTAT_df.shape)
print(neighborhood_ELSTAT_df.columns)
neighborhood_ELSTAT_df.head()

(48, 31)
Index(['Municipal Community', 'Neighborhood', 'Centroid_x', 'Centroid_y',
       'Neighborhood_Area_km2', 'Geometry', 'distance_to_volos_center_km',
       'distance_to_volos_port_km', 'dist_to_main_road_km',
       'dist_to_bus_stop_km', 'dist_to_university_km', 'ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ',
       'ΔΗΜΟΣ', 'ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ', 'Population', 'Άγαμοι_pct', 'Έγγαμοι_pct',
       'Χήροι_pct', 'Διαζευγμένοι_pct', 'age_0_14_pct', 'age_15_64_pct',
       'age_65_plus_pct', 'low_education_pct', 'medium_education_pct',
       'high_education_pct', 'unemployment_rate',
       'labor_force_participation_rate', 'primary_sector_pct',
       'secondary_sector_pct', 'tertiary_sector_pct', 'Area_km2'],
      dtype='object')

,Municipal Community,Neighborhood,Centroid_x,Centroid_y,Neighborhood_Area_km2,Geometry,distance_to_volos_center_km,distance_to_volos_port_km,dist_to_main_road_km,dist_to_bus_stop_km,...,age_65_plus_pct,low_education_pct,medium_education_pct,high_education_pct,unemployment_rate,labor_force_participation_rate,primary_sector_pct,secondary_sector_pct,tertiary_sector_pct,Area_km2
0,Municipal Community of Dimini,Dimini,22.882945,39.349112,37.344776,MULTIPOLYGON (((406692.718139543 4357521.85294...,6.154015,5.418577,0.443434,1.569912,...,0.2080,0.5437,0.3163,0.1395,0.2211,0.4327,0.1161,0.2365,0.6459,37.323451
1,Municipal Community of Sesklos,Xrisi Akti Panagias,22.836899,39.305430,9.983032,MULTIPOLYGON (((396744.165394512 4351195.65810...,11.932475,11.015584,2.299921,2.410375,...,0.2147,0.6009,0.2812,0.1179,0.1304,0.3838,0.1424,0.3609,0.4967,37.329725
2,Municipal Community of Sesklos,Sesklo,22.838168,39.353051,27.367312,MULTIPOLYGON (((400839.361742302 4353031.79092...,9.814666,9.191001,0.482308,4.965561,...,0.2147,0.6009,0.2812,0.1179,0.1304,0.3838,0.1424,0.3609,0.4967,37.329725
3,Municipal Community of Volos,Agioi Anargiroi,22.924059,39.366937,0.774436,MULTIPOLYGON (((406589.250339913 4357224.83344...,2.296184,1.978856,0.058142,0.063879,...,0.2221,0.3634,0.3663,0.2704,0.1545,0.4188,0.0313,0.1666,0.8022,26.790807
4,Municipal Community of Volos,Aivaliotika,22.922660,39.343696,4.848904,MULTIPOLYGON (((407619.510540358 4356306.42684...,3.508166,2.529372,0.224486,0.246542,...,0.2221,0.3634,0.3663,0.2704,0.1545,0.4188,0.0313,0.1666,0.8022,26.790807

## ***Compute the Statistics of the Neighborhoods***

In [10]:
# Neighborhood-level features
neighborhood_colls = [
    'Neighborhood_Area_km2', 'distance_to_volos_center_km',
    'distance_to_volos_port_km', 'dist_to_main_road_km',
    'dist_to_bus_stop_km', 'dist_to_university_km',
]

# Municipal-Community-level Features
municipal_community_colls = [
    'Population', 'Άγαμοι_pct', 'Έγγαμοι_pct',
    'Χήροι_pct', 'Διαζευγμένοι_pct', 'age_0_14_pct', 'age_15_64_pct',
    'age_65_plus_pct', 'low_education_pct', 'medium_education_pct',
    'high_education_pct', 'unemployment_rate',
    'labor_force_participation_rate', 'primary_sector_pct',
    'secondary_sector_pct', 'tertiary_sector_pct', 
    #'Area_km2'
]

# Combine all feature columns
all_feature_cols = neighborhood_colls + municipal_community_colls

In [11]:
neighborhood_stats = compute_features_stats(neighborhood_ELSTAT_df, neighborhood_colls)

In [12]:
municipal_community_stats = compute_features_stats(municipal_community_df, municipal_community_colls)

In [13]:
# Fixed features to always include in the completion text
fixed_features = [
    "Neighborhood_Area_km2",
    "distance_to_volos_center_km",
    "distance_to_volos_port_km",
    "dist_to_main_road_km",
    "dist_to_bus_stop_km",
    "dist_to_university_km",
    "Population",
]

## ***Create a Description for each Neighborhood***

In [14]:
descriptions = []

max_reasons = 20

for _, row in neighborhood_df.iterrows():

    neighborhood_name = row['Neighborhood']

    # extract the features for this neighborhood
    features = extract_neighborhood_features(
        neighborhood_name=neighborhood_name,
        neighborhood_ELSTAT_df=neighborhood_ELSTAT_df,
        feature_cols=all_feature_cols
    )

    # create the description for this neighborhood
    description = justify_neighborhood(
        neighborhood_name,
        neighborhood_stats, 
        municipal_community_stats, 
        neighborhood_colls, 
        municipal_community_colls,
        all_features=features,
        fixed_features=fixed_features,
        max_reasons=max_reasons
    )    
    
    descriptions.append({
        "Neighborhood": neighborhood_name,
        "Description": description
    })
    
descriptions_df = pd.DataFrame(descriptions)

## ***Save the Data***

In [15]:
descriptions_df.to_csv("C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\8. LLM - RAG\\Extracted Files\\Neighborhood Descriptions\\neighborhood_descriptions_" + str(max_reasons) + ".csv", index=False)