So far i have cleaned and merged the data, filling the missing values i could find and deleting the ones i could not or were invalid. Now i want to integrate the NACE column. I think i must first examine the 'Category' feature

## ***Initials***

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## ***Load the Data***

In [13]:
df = pd.read_csv("C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\2. Base Datasets\\3. Merging - Business Data\\Extracted CSV Files\\business_data.csv")
print(len(df))
df.head()

3906

,Name,Category,Latitude,Longitude,Address,Country,City,Postal Code,Rating,Reviews,Source,Description
0,Άνθη-φυτά,Flower Store,39.335293,22.923506,6χλ.βολου,Greece,Βόλος Μαγνησίας,38334,NaN,NaN,foursquare,NaN
1,Μέταλλο και ξύλο,Furniture and Home Store,39.339233,22.923969,Βόλου - Αθηνών 7ο χλμ,Greece,Βόλος Μαγνησίας,38334,NaN,NaN,foursquare,NaN
2,Προφήτης Ηλίας Αλυκών,Church,39.332305,22.926496,Λεωφόρος Αθηνών 155,Greece,Βόλος Μαγνησίας,38334,NaN,NaN,foursquare,NaN
3,Frago Cargo (Φραγγοσ Νικολαοσ),"Shipping, Freight, and Material Transportation...",39.332756,22.929457,Αλόης 179Γ,Greece,Βόλος Μαγνησίας,38334,NaN,NaN,foursquare,NaN
4,Αλφα Ωμεγα Express Market,Grocery Store,39.332876,22.929374,Βάκχου 4,Greece,Βόλος Μαγνησίας,38334,NaN,NaN,foursquare,NaN

## ***Inspect the Feature: 'Category' - Create 'categories.csv'***

In [8]:
categories = df['Category'].dropna().unique()
print(len(categories))
print(sorted(categories))

1239

Create the file that contains all the unique categories. They will be MANUALLY mapped to their corresponding NACE Code later

In [ ]:
df['Category'].value_counts().to_csv("categories.csv")

## ***Add the Features: 'NACE Code' / 'NACE Description (EN)'***

I ***manually*** performed the Category - NACE mapping in "categories.csv". I used a ***spatial join*** to add the columns "NACE Code" / "NACE Description (EN)", probably ***off-screen***.

I see 6 entries with missing values in these columns, but i will add them manually

In [8]:
df = pd.read_csv("C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\2. Base Datasets\\6. Joining - Business Data - NACE\\Extracted CSV Files\\business_data.csv")
print(len(df))
df.head()

3906

,Name,Category,Latitude,Longitude,Address,Country,City,Postal Code,Rating,Reviews,Source,Description,NACE Code,NACE Description (EN)
0,Άνθη-φυτά,Flower Store,39.335293,22.923506,6χλ.βολου,Greece,Βόλος Μαγνησίας,38334,NaN,NaN,foursquare,NaN,47.76,"Retail sale of flowers, plants, seeds, fertili..."
1,Μέταλλο και ξύλο,Furniture and Home Store,39.339233,22.923969,Βόλου - Αθηνών 7ο χλμ,Greece,Βόλος Μαγνησίας,38334,NaN,NaN,foursquare,NaN,47.59,"Retail sale of furniture, lighting equipment a..."
2,Προφήτης Ηλίας Αλυκών,Church,39.332305,22.926496,Λεωφόρος Αθηνών 155,Greece,Βόλος Μαγνησίας,38334,NaN,NaN,foursquare,NaN,94.91,Activities of religious organisations
3,Frago Cargo (Φραγγοσ Νικολαοσ),"Shipping, Freight, and Material Transportation...",39.332756,22.929457,Αλόης 179Γ,Greece,Βόλος Μαγνησίας,38334,NaN,NaN,foursquare,NaN,49.41,Freight transport by road
4,Αλφα Ωμεγα Express Market,Grocery Store,39.332876,22.929374,Βάκχου 4,Greece,Βόλος Μαγνησίας,38334,NaN,NaN,foursquare,NaN,47.11,Retail sale in non-specialised stores with foo...

In [16]:
no_NACE_df = df[df['NACE Code'].isna()]
print(len(no_NACE_df))
no_NACE_df.head(30)

0

Empty DataFrame
Columns: [Unnamed: 0, Name, Category, Latitude, Longitude, Address, Country, City, Postal Code, Rating, Reviews, Source, Description, NACE Code, NACE Description (EN)]
Index: []