## ***Initials***

In [1]:
import pandas as pd

## ***Load the Data***

In [ ]:
df = pd.read_csv("C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\5. Neighborhoods\\neighborhoods.csv")
print(len(df))
df.head()

48

,WKT,fid,community,point_name,method,full_id,osm_id,osm_type,place,name,...,name_el,int_name,addr_postc,alt_name,layer,path,point_id,centroid_x,centroid_y,area
0,MULTIPOLYGON (((406692.718139543 4357521.85294...,1,Δημοτική Κοινότητα Διμηνίου,Δημίνι,no points,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.882945,39.349112,37.344776
1,MULTIPOLYGON (((396744.165394512 4351195.65810...,2,Δημοτική Κοινότητα Σέσκλου,Χρυσή Ακτή Παναγίας,2-point split,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.836899,39.305430,9.983032
2,MULTIPOLYGON (((400839.361742302 4353031.79092...,3,Δημοτική Κοινότητα Σέσκλου,Σέσκλο,2-point split,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.838168,39.353051,27.367312
3,MULTIPOLYGON (((406589.250339913 4357224.83344...,4,Δημοτική Κοινότητα Βόλου,Άγιοι Ανάργυροι,NaN,n9727430188,9.727430e+09,node,neighbourhood,Άγιοι Ανάργυροι,...,NaN,NaN,NaN,NaN,place_neighbourhood_Volos,"Point?crs=EPSG:4326&field=full_id:string(0,0)&...",NaN,22.924059,39.366937,0.774436
4,MULTIPOLYGON (((407619.510540358 4356306.42684...,5,Δημοτική Κοινότητα Βόλου,Αϊβαλιώτικα,NaN,n9729650302,9.729650e+09,node,neighbourhood,Αϊβαλιώτικα,...,NaN,NaN,NaN,NaN,place_neighbourhood_Volos,"Point?crs=EPSG:4326&field=full_id:string(0,0)&...",NaN,22.922660,39.343696,4.848904

## ***Clean the Data***

In [20]:
# Keep only the necessary columns
keep_cols = [
    'community', 'point_name',
    'centroid_x', 'centroid_y', 'area',
    'WKT'
]

In [21]:
cleaned_df = df[keep_cols].copy()
print(len(cleaned_df))

48

In [22]:
cleaned_df.rename(columns={'community': 'Municipal Community', 'point_name': 'Name'}, inplace=True)

In [23]:
cleaned_df.head()

,Municipal Community,Name,centroid_x,centroid_y,area,WKT
0,Δημοτική Κοινότητα Διμηνίου,Δημίνι,22.882945,39.349112,37.344776,MULTIPOLYGON (((406692.718139543 4357521.85294...
1,Δημοτική Κοινότητα Σέσκλου,Χρυσή Ακτή Παναγίας,22.836899,39.305430,9.983032,MULTIPOLYGON (((396744.165394512 4351195.65810...
2,Δημοτική Κοινότητα Σέσκλου,Σέσκλο,22.838168,39.353051,27.367312,MULTIPOLYGON (((400839.361742302 4353031.79092...
3,Δημοτική Κοινότητα Βόλου,Άγιοι Ανάργυροι,22.924059,39.366937,0.774436,MULTIPOLYGON (((406589.250339913 4357224.83344...
4,Δημοτική Κοινότητα Βόλου,Αϊβαλιώτικα,22.922660,39.343696,4.848904,MULTIPOLYGON (((407619.510540358 4356306.42684...

In [25]:
# Save to new file
cleaned_df.to_csv("neighborhoods_cleaned.csv", index=False)