In [65]:
import geopandas as gpd
import pandas as pd

In [78]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## ***emporiko***

In [79]:
name = "emporiko"

In [80]:
# Load the shapefile
df = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/geocoded-initial/geocoded-" + name +".csv")
print(f"samples: ", len(df))
df.head()

samples:  12417

,full addre,city,country,active yea,real succe,predicted,result_num,osm_id,display_na,category,type,latlong,successful,pred_suc
0,"Γ. ΙΜΒΡΙΩΤΗ 7, 38500",Volos,Greece,14.661191,0.276112,0.651447,0,31796392,"Ιμβριώτη Γ., Άγιος Γεώργιος, Ιωλκός, Δήμος Βόλ...",highway,residential,"39.373205635564766,22.961625479839267",1,1
1,"ΑΛΕΞΑΝΔΡΑΣ 177, 38221",Volos,Greece,14.806297,0.278892,0.741244,0,958294762,"28ης Οκτωβρίου, Άγιος Νικόλαος, Νέα Ιωνία, Δήμ...",highway,residential,"39.36107061861301,22.949440362185836",1,1
2,"ΑΛΕΞΑΝΔΡΑΣ 177, 38221",Volos,Greece,14.806297,0.278892,0.741244,1,958295312,"28ης Οκτωβρίου, Μεταμόρφωση, Νέα Ιωνία, Δήμος ...",highway,residential,"39.361974628107596,22.94786038431433",1,1
3,"ΑΛΕΞΑΝΔΡΑΣ 177, 38221",Volos,Greece,14.806297,0.278892,0.741244,2,958294761,"28ης Οκτωβρίου, Οξυγόνο, Νέα Ιωνία, Δήμος Βόλο...",highway,residential,"39.36445295550105,22.943562511396788",1,1
4,"ΑΛΕΞΑΝΔΡΑΣ 177, 38221",Volos,Greece,14.806297,0.278892,0.741244,3,243323310,"28ης Οκτωβρίου, Άγιος Κωνσταντίνος, Ιωλκός, Δή...",highway,residential,"39.357800005511876,22.95589115270792",1,1

In [81]:
df_clean = df.drop_duplicates(subset=['full addre'], keep='first')
print(len(df_clean))

3099

In [82]:
df_clean[['latitude', 'longitude']] = df_clean['latlong'].str.split(',', expand=True)

# Convert to float
df_clean['latitude'] = df_clean['latitude'].astype(float)
df_clean['longitude'] = df_clean['longitude'].astype(float)
df_clean.head()

<ipython-input-82-ea7709cca512>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[['latitude', 'longitude']] = df_clean['latlong'].str.split(',', expand=True)
<ipython-input-82-ea7709cca512>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[['latitude', 'longitude']] = df_clean['latlong'].str.split(',', expand=True)
<ipython-input-82-ea7709cca512>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['latitude'] = df_clean['latitude'].astype(float)
<ipython-input-82-ea7709cca512>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['longitude'] = df_clean['longitude'].astype(float)

,full addre,city,country,active yea,real succe,predicted,result_num,osm_id,display_na,category,type,latlong,successful,pred_suc,latitude,longitude
0,"Γ. ΙΜΒΡΙΩΤΗ 7, 38500",Volos,Greece,14.661191,0.276112,0.651447,0,31796392,"Ιμβριώτη Γ., Άγιος Γεώργιος, Ιωλκός, Δήμος Βόλ...",highway,residential,"39.373205635564766,22.961625479839267",1,1,39.373206,22.961625
1,"ΑΛΕΞΑΝΔΡΑΣ 177, 38221",Volos,Greece,14.806297,0.278892,0.741244,0,958294762,"28ης Οκτωβρίου, Άγιος Νικόλαος, Νέα Ιωνία, Δήμ...",highway,residential,"39.36107061861301,22.949440362185836",1,1,39.361071,22.949440
5,"ΜΑΙΑΝΔΡΟΥ 21, 38445",Volos,Greece,8.821355,0.164251,0.755309,0,37058611,"Μαιάνδρου, Άγιοι Ανάργυροι, Νέα Ιωνία, Δήμος Β...",highway,residential,"39.37137400240597,22.925663515695703",1,1,39.371374,22.925664
9,"ΚΩΝΣΤΑΝΤΑ 136Ε, 38221",Volos,Greece,2.431211,0.041849,0.733311,0,31712420,"Κωνσταντά, Ανάληψη, Νέα Ιωνία, Δήμος Βόλου, Πε...",highway,tertiary,"39.36287374518561,22.951607661212247",0,1,39.362874,22.951608
12,"ΠΛΑΤΩΝΟΣ 34, 38222",Volos,Greece,10.165640,0.190001,0.689946,0,574209185,"Πλάτωνος, Μεταμόρφωση, Νέα Ιωνία, Δήμος Βόλου,...",highway,living_street,"39.362484949999995,22.94574595",1,1,39.362485,22.945746

In [83]:
df_clean = df_clean[['full addre', 'city', 'country', 'latitude', 'longitude', 'active yea', 'successful', 'predicted', 'pred_suc', 'osm_id', 'display_na', 'category', 'type']]
df_clean.rename(columns={'full addre': 'full adress'}, inplace=True)
df_clean.rename(columns={'active yea': 'active years'}, inplace=True)
df_clean.rename(columns={'successful': 'success'}, inplace=True)
df_clean.rename(columns={'predicted': 'predicted success prob'}, inplace=True)
df_clean.rename(columns={'pred_suc': 'predicted success'}, inplace=True)
df_clean.head()

<ipython-input-83-22cb0b892331>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.rename(columns={'full addre': 'full adress'}, inplace=True)
<ipython-input-83-22cb0b892331>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.rename(columns={'active yea': 'active years'}, inplace=True)
<ipython-input-83-22cb0b892331>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.rename(columns={'successful': 'success'}, inplace=True)
<ipython-input-83-22cb0b892331>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.rename(columns={'predicted': 'predicted success prob'}, inplace=True)
<ipython-input-83-22cb0b892331>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.rename(columns={'pred_suc': 'predicted success'}, inplace=True)

,full adress,city,country,latitude,longitude,active years,success,predicted success prob,predicted success,osm_id,display_na,category,type
0,"Γ. ΙΜΒΡΙΩΤΗ 7, 38500",Volos,Greece,39.373206,22.961625,14.661191,1,0.651447,1,31796392,"Ιμβριώτη Γ., Άγιος Γεώργιος, Ιωλκός, Δήμος Βόλ...",highway,residential
1,"ΑΛΕΞΑΝΔΡΑΣ 177, 38221",Volos,Greece,39.361071,22.949440,14.806297,1,0.741244,1,958294762,"28ης Οκτωβρίου, Άγιος Νικόλαος, Νέα Ιωνία, Δήμ...",highway,residential
5,"ΜΑΙΑΝΔΡΟΥ 21, 38445",Volos,Greece,39.371374,22.925664,8.821355,1,0.755309,1,37058611,"Μαιάνδρου, Άγιοι Ανάργυροι, Νέα Ιωνία, Δήμος Β...",highway,residential
9,"ΚΩΝΣΤΑΝΤΑ 136Ε, 38221",Volos,Greece,39.362874,22.951608,2.431211,0,0.733311,1,31712420,"Κωνσταντά, Ανάληψη, Νέα Ιωνία, Δήμος Βόλου, Πε...",highway,tertiary
12,"ΠΛΑΤΩΝΟΣ 34, 38222",Volos,Greece,39.362485,22.945746,10.165640,1,0.689946,1,574209185,"Πλάτωνος, Μεταμόρφωση, Νέα Ιωνία, Δήμος Βόλου,...",highway,living_street

In [84]:
df_clean.to_csv(f'geocoded-' + name + '.csv', index=False)

## ***metapoiitiko***

In [87]:
name = "metapoiitiko"

In [88]:
# Load the shapefile
df = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/geocoded-initial/geocoded-" + name +".csv")
print(f"samples: ", len(df))
df.head()

samples:  718

,full addre,city,country,active yea,real succe,predicted,result_num,osm_id,display_na,category,type,latlong,successful,pred_suc
0,"ΤΡΑΠΕΖΟΥΝΤΟΣ 25, 38445",Volos,Greece,6.699521,0.123608,0.736039,0,31797455,"Τραπεζούντος, Άγιοι Ανάργυροι, Νέα Ιωνία, Δήμο...",highway,residential,"39.37202425310636,22.926259157865854",1,1
1,"ΣΟΛΩΝΟΣ 16, 38333",Volos,Greece,4.717317,0.085639,0.726709,0,290903166,"Σόλωνος, Μεταμόρφωση, Νέα Ιωνία, Δήμος Βόλου, ...",highway,pedestrian,"39.36301058100164,22.943931260727798",1,1
2,"ΝΙΚΟΜΗΔΕΙΑΣ 2, 38446",Volos,Greece,2.242300,0.038231,0.729119,0,11614901388,"ΚΕΠ ΒΟΛΟΥ, 2, Νικομήδειας, Νέα Ιωνία, Δήμος Βό...",office,government,"39.372257,22.9384931",0,1
3,"ΜΑΝΤΖΑΡΟΥ 8, 38222",Volos,Greece,10.332649,0.193200,0.767770,0,579391578,"Μάντζαρου Νικ., Καραγάτς, Ιωλκός, Δήμος Βόλου,...",highway,pedestrian,"39.3630900755131,22.96290461655467",1,1
4,"ΑΦΡΟΔΙΤΗΣ 21, 38222",Volos,Greece,14.896646,0.280622,0.738215,0,579286638,"Αφροδίτης, Νέα Δημητριάδα, Ιωλκός, Δήμος Βόλου...",highway,residential,"39.36066152150518,22.96867676595821",1,1

In [89]:
df_clean = df.drop_duplicates(subset=['full addre'], keep='first')
print(len(df_clean))

613

In [90]:
df_clean[['latitude', 'longitude']] = df_clean['latlong'].str.split(',', expand=True)

# Convert to float
df_clean['latitude'] = df_clean['latitude'].astype(float)
df_clean['longitude'] = df_clean['longitude'].astype(float)
df_clean.head()

<ipython-input-90-ea7709cca512>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[['latitude', 'longitude']] = df_clean['latlong'].str.split(',', expand=True)
<ipython-input-90-ea7709cca512>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[['latitude', 'longitude']] = df_clean['latlong'].str.split(',', expand=True)
<ipython-input-90-ea7709cca512>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['latitude'] = df_clean['latitude'].astype(float)
<ipython-input-90-ea7709cca512>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['longitude'] = df_clean['longitude'].astype(float)

,full addre,city,country,active yea,real succe,predicted,result_num,osm_id,display_na,category,type,latlong,successful,pred_suc,latitude,longitude
0,"ΤΡΑΠΕΖΟΥΝΤΟΣ 25, 38445",Volos,Greece,6.699521,0.123608,0.736039,0,31797455,"Τραπεζούντος, Άγιοι Ανάργυροι, Νέα Ιωνία, Δήμο...",highway,residential,"39.37202425310636,22.926259157865854",1,1,39.372024,22.926259
1,"ΣΟΛΩΝΟΣ 16, 38333",Volos,Greece,4.717317,0.085639,0.726709,0,290903166,"Σόλωνος, Μεταμόρφωση, Νέα Ιωνία, Δήμος Βόλου, ...",highway,pedestrian,"39.36301058100164,22.943931260727798",1,1,39.363011,22.943931
2,"ΝΙΚΟΜΗΔΕΙΑΣ 2, 38446",Volos,Greece,2.242300,0.038231,0.729119,0,11614901388,"ΚΕΠ ΒΟΛΟΥ, 2, Νικομήδειας, Νέα Ιωνία, Δήμος Βό...",office,government,"39.372257,22.9384931",0,1,39.372257,22.938493
3,"ΜΑΝΤΖΑΡΟΥ 8, 38222",Volos,Greece,10.332649,0.193200,0.767770,0,579391578,"Μάντζαρου Νικ., Καραγάτς, Ιωλκός, Δήμος Βόλου,...",highway,pedestrian,"39.3630900755131,22.96290461655467",1,1,39.363090,22.962905
4,"ΑΦΡΟΔΙΤΗΣ 21, 38222",Volos,Greece,14.896646,0.280622,0.738215,0,579286638,"Αφροδίτης, Νέα Δημητριάδα, Ιωλκός, Δήμος Βόλου...",highway,residential,"39.36066152150518,22.96867676595821",1,1,39.360662,22.968677

In [91]:
df_clean = df_clean[['full addre', 'city', 'country', 'latitude', 'longitude', 'active yea', 'successful', 'predicted', 'pred_suc', 'osm_id', 'display_na', 'category', 'type']]
df_clean.rename(columns={'full addre': 'full adress'}, inplace=True)
df_clean.rename(columns={'active yea': 'active years'}, inplace=True)
df_clean.rename(columns={'successful': 'success'}, inplace=True)
df_clean.rename(columns={'predicted': 'predicted success prob'}, inplace=True)
df_clean.rename(columns={'pred_suc': 'predicted success'}, inplace=True)
df_clean.head()

,full adress,city,country,latitude,longitude,active years,success,predicted success prob,predicted success,osm_id,display_na,category,type
0,"ΤΡΑΠΕΖΟΥΝΤΟΣ 25, 38445",Volos,Greece,39.372024,22.926259,6.699521,1,0.736039,1,31797455,"Τραπεζούντος, Άγιοι Ανάργυροι, Νέα Ιωνία, Δήμο...",highway,residential
1,"ΣΟΛΩΝΟΣ 16, 38333",Volos,Greece,39.363011,22.943931,4.717317,1,0.726709,1,290903166,"Σόλωνος, Μεταμόρφωση, Νέα Ιωνία, Δήμος Βόλου, ...",highway,pedestrian
2,"ΝΙΚΟΜΗΔΕΙΑΣ 2, 38446",Volos,Greece,39.372257,22.938493,2.242300,0,0.729119,1,11614901388,"ΚΕΠ ΒΟΛΟΥ, 2, Νικομήδειας, Νέα Ιωνία, Δήμος Βό...",office,government
3,"ΜΑΝΤΖΑΡΟΥ 8, 38222",Volos,Greece,39.363090,22.962905,10.332649,1,0.767770,1,579391578,"Μάντζαρου Νικ., Καραγάτς, Ιωλκός, Δήμος Βόλου,...",highway,pedestrian
4,"ΑΦΡΟΔΙΤΗΣ 21, 38222",Volos,Greece,39.360662,22.968677,14.896646,1,0.738215,1,579286638,"Αφροδίτης, Νέα Δημητριάδα, Ιωλκός, Δήμος Βόλου...",highway,residential

In [92]:
df_clean.to_csv(f'geocoded-' + name + '.csv', index=False)

## ***touristiko***

In [93]:
name = "touristiko"

In [94]:
# Load the shapefile
df = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/geocoded-initial/geocoded-" + name +".csv")
print(f"samples: ", len(df))
df.head()

samples:  86

,full addre,city,country,active yea,real succe,predicted,result_num,osm_id,display_na,category,type,latlong,successful,pred_suc
0,"ΒΕΝΙΖΕΛΟΥ 67, 38221",Volos,Greece,43.887748,0.835941,0.788468,0,31745671,"Βενιζέλου, Άγιοι Ανάργυροι, Νέα Ιωνία, Δήμος Β...",highway,tertiary,"39.3713094,22.9330249",1,1
1,"ΚΥΠΡΟΥ 5Δ, 38221",Volos,Greece,30.565366,0.580754,0.807303,0,31796013,"Κύπρου, Άγιος Νικόλαος, Ιωλκός, Δήμος Βόλου, Π...",highway,residential,"39.3655071,22.9526995",1,1
2,"ΚΑΣΣΑΒΕΤΗ 1, 38221",Volos,Greece,23.230664,0.440259,0.800626,0,344086200,"1, Κασσαβέτη, Άγιος Κωνσταντίνος, Ιωλκός, Δήμο...",building,yes,"39.3573421,22.95412331791145",1,1
3,"ΚΟΥΜΟΥΝΔΟΥΡΟΥ 20, 38221",Volos,Greece,20.429843,0.386610,0.779857,0,43363730,"Κουμουνδούρου, Άγιος Νικόλαος, Νέα Ιωνία, Δήμο...",highway,living_street,"39.3597732,22.9499286",1,1
4,"ΓΚΛΑΒΑΝΗ 36Α, 38221",Volos,Greece,18.781656,0.355039,0.749951,0,31758225,"Γκλαβάνη, Άγιος Νικόλαος, Νέα Ιωνία, Δήμος Βόλ...",highway,residential,"39.3600126,22.9494351",1,1

In [95]:
df_clean = df.drop_duplicates(subset=['full addre'], keep='first')
print(len(df_clean))

75

In [96]:
df_clean[['latitude', 'longitude']] = df_clean['latlong'].str.split(',', expand=True)

# Convert to float
df_clean['latitude'] = df_clean['latitude'].astype(float)
df_clean['longitude'] = df_clean['longitude'].astype(float)
df_clean.head()

<ipython-input-96-ea7709cca512>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[['latitude', 'longitude']] = df_clean['latlong'].str.split(',', expand=True)
<ipython-input-96-ea7709cca512>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[['latitude', 'longitude']] = df_clean['latlong'].str.split(',', expand=True)
<ipython-input-96-ea7709cca512>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['latitude'] = df_clean['latitude'].astype(float)
<ipython-input-96-ea7709cca512>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['longitude'] = df_clean['longitude'].astype(float)

,full addre,city,country,active yea,real succe,predicted,result_num,osm_id,display_na,category,type,latlong,successful,pred_suc,latitude,longitude
0,"ΒΕΝΙΖΕΛΟΥ 67, 38221",Volos,Greece,43.887748,0.835941,0.788468,0,31745671,"Βενιζέλου, Άγιοι Ανάργυροι, Νέα Ιωνία, Δήμος Β...",highway,tertiary,"39.3713094,22.9330249",1,1,39.371309,22.933025
1,"ΚΥΠΡΟΥ 5Δ, 38221",Volos,Greece,30.565366,0.580754,0.807303,0,31796013,"Κύπρου, Άγιος Νικόλαος, Ιωλκός, Δήμος Βόλου, Π...",highway,residential,"39.3655071,22.9526995",1,1,39.365507,22.952700
2,"ΚΑΣΣΑΒΕΤΗ 1, 38221",Volos,Greece,23.230664,0.440259,0.800626,0,344086200,"1, Κασσαβέτη, Άγιος Κωνσταντίνος, Ιωλκός, Δήμο...",building,yes,"39.3573421,22.95412331791145",1,1,39.357342,22.954123
3,"ΚΟΥΜΟΥΝΔΟΥΡΟΥ 20, 38221",Volos,Greece,20.429843,0.386610,0.779857,0,43363730,"Κουμουνδούρου, Άγιος Νικόλαος, Νέα Ιωνία, Δήμο...",highway,living_street,"39.3597732,22.9499286",1,1,39.359773,22.949929
4,"ΓΚΛΑΒΑΝΗ 36Α, 38221",Volos,Greece,18.781656,0.355039,0.749951,0,31758225,"Γκλαβάνη, Άγιος Νικόλαος, Νέα Ιωνία, Δήμος Βόλ...",highway,residential,"39.3600126,22.9494351",1,1,39.360013,22.949435

In [97]:
df_clean = df_clean[['full addre', 'city', 'country', 'latitude', 'longitude', 'active yea', 'successful', 'predicted', 'pred_suc', 'osm_id', 'display_na', 'category', 'type']]
df_clean.rename(columns={'full addre': 'full adress'}, inplace=True)
df_clean.rename(columns={'active yea': 'active years'}, inplace=True)
df_clean.rename(columns={'successful': 'success'}, inplace=True)
df_clean.rename(columns={'predicted': 'predicted success prob'}, inplace=True)
df_clean.rename(columns={'pred_suc': 'predicted success'}, inplace=True)
df_clean.head()

,full adress,city,country,latitude,longitude,active years,success,predicted success prob,predicted success,osm_id,display_na,category,type
0,"ΒΕΝΙΖΕΛΟΥ 67, 38221",Volos,Greece,39.371309,22.933025,43.887748,1,0.788468,1,31745671,"Βενιζέλου, Άγιοι Ανάργυροι, Νέα Ιωνία, Δήμος Β...",highway,tertiary
1,"ΚΥΠΡΟΥ 5Δ, 38221",Volos,Greece,39.365507,22.952700,30.565366,1,0.807303,1,31796013,"Κύπρου, Άγιος Νικόλαος, Ιωλκός, Δήμος Βόλου, Π...",highway,residential
2,"ΚΑΣΣΑΒΕΤΗ 1, 38221",Volos,Greece,39.357342,22.954123,23.230664,1,0.800626,1,344086200,"1, Κασσαβέτη, Άγιος Κωνσταντίνος, Ιωλκός, Δήμο...",building,yes
3,"ΚΟΥΜΟΥΝΔΟΥΡΟΥ 20, 38221",Volos,Greece,39.359773,22.949929,20.429843,1,0.779857,1,43363730,"Κουμουνδούρου, Άγιος Νικόλαος, Νέα Ιωνία, Δήμο...",highway,living_street
4,"ΓΚΛΑΒΑΝΗ 36Α, 38221",Volos,Greece,39.360013,22.949435,18.781656,1,0.749951,1,31758225,"Γκλαβάνη, Άγιος Νικόλαος, Νέα Ιωνία, Δήμος Βόλ...",highway,residential

In [98]:
df_clean.to_csv(f'geocoded-' + name + '.csv', index=False)

## ***ypiresion***

In [99]:
name = "ypiresion"

In [100]:
# Load the shapefile
df = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/geocoded-initial/geocoded-" + name +".csv")
print(f"samples: ", len(df))
df.head()

samples:  5384

,full addre,city,country,active yea,real succe,predicted,result_num,osm_id,display_na,category,type,latlong,successful,pred_suc
0,"ΝΙΚΟΤΣΑΡΑ 44, 38221",Volos,Greece,21.349760,0.404230,0.751705,0,406851368,"Νικοτσάρα, Άγιος Κωνσταντίνος, Ιωλκός, Δήμος Β...",highway,residential,"39.35672205,22.955302099999997",1,1
1,"ΦΙΛΑΡΕΤΟΥ 6, 38333",Volos,Greece,7.488022,0.138712,0.766852,0,31758329,"Φιλαρέτου, Χιλιαδού, Νέα Ιωνία, Δήμος Βόλου, Π...",highway,residential,"39.37410648489988,22.947065511667343",1,1
2,"ΠΗΛΙΟΥ 37, 38333",Volos,Greece,9.672827,0.180561,0.747742,0,579411504,"Πηλίου, Χιλιαδού, Ιωλκός, Δήμος Βόλου, Περιφερ...",highway,residential,"39.37208648219002,22.953289505710455",1,1
3,"ΦΙΛΑΡΕΤΟΥ 6, 38333",Volos,Greece,10.217659,0.190997,0.759511,0,31758329,"Φιλαρέτου, Χιλιαδού, Νέα Ιωνία, Δήμος Βόλου, Π...",highway,residential,"39.37410648489988,22.947065511667343",1,1
4,"ΠΑΥΛΟΥ ΜΕΛΑ 65Α, 38333",Volos,Greece,8.399726,0.156175,0.793843,0,31712116,"Παύλου Μελά, Μεταμόρφωση, Νέα Ιωνία, Δήμος Βόλ...",highway,residential,"39.36249410584218,22.945964557876326",1,1

In [101]:
df_clean = df.drop_duplicates(subset=['full addre'], keep='first')
print(len(df_clean))

4007

In [102]:
df_clean[['latitude', 'longitude']] = df_clean['latlong'].str.split(',', expand=True)

# Convert to float
df_clean['latitude'] = df_clean['latitude'].astype(float)
df_clean['longitude'] = df_clean['longitude'].astype(float)
df_clean.head()

<ipython-input-102-ea7709cca512>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[['latitude', 'longitude']] = df_clean['latlong'].str.split(',', expand=True)
<ipython-input-102-ea7709cca512>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[['latitude', 'longitude']] = df_clean['latlong'].str.split(',', expand=True)
<ipython-input-102-ea7709cca512>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['latitude'] = df_clean['latitude'].astype(float)
<ipython-input-102-ea7709cca512>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['longitude'] = df_clean['longitude'].astype(float)

,full addre,city,country,active yea,real succe,predicted,result_num,osm_id,display_na,category,type,latlong,successful,pred_suc,latitude,longitude
0,"ΝΙΚΟΤΣΑΡΑ 44, 38221",Volos,Greece,21.349760,0.404230,0.751705,0,406851368,"Νικοτσάρα, Άγιος Κωνσταντίνος, Ιωλκός, Δήμος Β...",highway,residential,"39.35672205,22.955302099999997",1,1,39.356722,22.955302
1,"ΦΙΛΑΡΕΤΟΥ 6, 38333",Volos,Greece,7.488022,0.138712,0.766852,0,31758329,"Φιλαρέτου, Χιλιαδού, Νέα Ιωνία, Δήμος Βόλου, Π...",highway,residential,"39.37410648489988,22.947065511667343",1,1,39.374106,22.947066
2,"ΠΗΛΙΟΥ 37, 38333",Volos,Greece,9.672827,0.180561,0.747742,0,579411504,"Πηλίου, Χιλιαδού, Ιωλκός, Δήμος Βόλου, Περιφερ...",highway,residential,"39.37208648219002,22.953289505710455",1,1,39.372086,22.953290
4,"ΠΑΥΛΟΥ ΜΕΛΑ 65Α, 38333",Volos,Greece,8.399726,0.156175,0.793843,0,31712116,"Παύλου Μελά, Μεταμόρφωση, Νέα Ιωνία, Δήμος Βόλ...",highway,residential,"39.36249410584218,22.945964557876326",1,1,39.362494,22.945965
5,"2ας ΝΟΕΜΒΡΙΟΥ 4, 38333",Volos,Greece,35.991786,0.684696,0.621369,0,1076091296,"4, 2ας Νοεμβρίου, Οξυγόνο, Νέα Ιωνία, Δήμος Βό...",place,house,"39.3698246,22.936231033333335",1,1,39.369825,22.936231

In [103]:
df_clean = df_clean[['full addre', 'city', 'country', 'latitude', 'longitude', 'active yea', 'successful', 'predicted', 'pred_suc', 'osm_id', 'display_na', 'category', 'type']]
df_clean.rename(columns={'full addre': 'full adress'}, inplace=True)
df_clean.rename(columns={'active yea': 'active years'}, inplace=True)
df_clean.rename(columns={'successful': 'success'}, inplace=True)
df_clean.rename(columns={'predicted': 'predicted success prob'}, inplace=True)
df_clean.rename(columns={'pred_suc': 'predicted success'}, inplace=True)
df_clean.head()

<ipython-input-103-22cb0b892331>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.rename(columns={'full addre': 'full adress'}, inplace=True)
<ipython-input-103-22cb0b892331>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.rename(columns={'active yea': 'active years'}, inplace=True)
<ipython-input-103-22cb0b892331>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.rename(columns={'successful': 'success'}, inplace=True)
<ipython-input-103-22cb0b892331>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.rename(columns={'predicted': 'predicted success prob'}, inplace=True)
<ipython-input-103-22cb0b892331>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.rename(columns={'pred_suc': 'predicted success'}, inplace=True)

,full adress,city,country,latitude,longitude,active years,success,predicted success prob,predicted success,osm_id,display_na,category,type
0,"ΝΙΚΟΤΣΑΡΑ 44, 38221",Volos,Greece,39.356722,22.955302,21.349760,1,0.751705,1,406851368,"Νικοτσάρα, Άγιος Κωνσταντίνος, Ιωλκός, Δήμος Β...",highway,residential
1,"ΦΙΛΑΡΕΤΟΥ 6, 38333",Volos,Greece,39.374106,22.947066,7.488022,1,0.766852,1,31758329,"Φιλαρέτου, Χιλιαδού, Νέα Ιωνία, Δήμος Βόλου, Π...",highway,residential
2,"ΠΗΛΙΟΥ 37, 38333",Volos,Greece,39.372086,22.953290,9.672827,1,0.747742,1,579411504,"Πηλίου, Χιλιαδού, Ιωλκός, Δήμος Βόλου, Περιφερ...",highway,residential
4,"ΠΑΥΛΟΥ ΜΕΛΑ 65Α, 38333",Volos,Greece,39.362494,22.945965,8.399726,1,0.793843,1,31712116,"Παύλου Μελά, Μεταμόρφωση, Νέα Ιωνία, Δήμος Βόλ...",highway,residential
5,"2ας ΝΟΕΜΒΡΙΟΥ 4, 38333",Volos,Greece,39.369825,22.936231,35.991786,1,0.621369,1,1076091296,"4, 2ας Νοεμβρίου, Οξυγόνο, Νέα Ιωνία, Δήμος Βό...",place,house

In [104]:
df_clean.to_csv(f'geocoded-' + name + '.csv', index=False)