# **initials**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
from transformers import pipeline
import pandas as pd

# ***load model***

In [ ]:
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

Device set to use cuda:0

In [ ]:
candidate_labels = ["success", "failure"]

# ***LLM prediction: ΤΟΥΡΙΣΤΙΚΟ***

In [ ]:
department="ΤΟΥΡΙΣΤΙΚΟ"

In [ ]:
df = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/LLM_prompt_data/data_LLM_" +department +".csv")
print(f"Total samples: ", len(df))
df.head()

Total samples:  143

                                        text_feature
0  Address: Γ. ΣΙΑΦΛΕΚΗ 8, Zip Code: 38222, City:...
1  Address: 28ΗΣ ΟΚΤΩΒΡΙΟΥ 155 - ΣΠ. ΣΠΥΡΙΔΗ, Zip...
2  Address: Σ. ΣΠΥΡΙΔΗ 96, Zip Code: 38221, City:...
3  Address: ΒΕΝΙΖΕΛΟΥ 67, Zip Code: 38221, City: ...
4  Address: ΚΥΠΡΟΥ 5Δ, Zip Code: 38221, City: ΒΟΛ...

In [ ]:
results = []

# predict each sample
for index, row in df.iterrows():

    # load LLM prompt
    text = row['text_feature']

    # get LLM prediction
    result = classifier(text, candidate_labels)

    # Store results
    results.append({
        'text': text,
        'success_probability': result['scores'][result['labels'].index("success")] if "success" in result['labels'] else None
    })

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [ ]:
results_df = pd.DataFrame(results)
results_df.head()

                                                text  success_probability
0  Address: Γ. ΣΙΑΦΛΕΚΗ 8, Zip Code: 38222, City:...             0.747190
1  Address: 28ΗΣ ΟΚΤΩΒΡΙΟΥ 155 - ΣΠ. ΣΠΥΡΙΔΗ, Zip...             0.689422
2  Address: Σ. ΣΠΥΡΙΔΗ 96, Zip Code: 38221, City:...             0.735422
3  Address: ΒΕΝΙΖΕΛΟΥ 67, Zip Code: 38221, City: ...             0.788468
4  Address: ΚΥΠΡΟΥ 5Δ, Zip Code: 38221, City: ΒΟΛ...             0.807303

In [ ]:
filename = f"LLM_prediction_{department}.csv"
results_df.to_csv(filename, index=False)
print(f"Saved {filename}")

Saved LLM_prediction_ΤΟΥΡΙΣΤΙΚΟ.csv

# ***LLM prediction: ΜΕΤΑΠΟΙΗΤΙΚΟ***

In [ ]:
department="ΜΕΤΑΠΟΙΗΤΙΚΟ"

In [ ]:
df = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/LLM_prompt_data/data_LLM_" +department +".csv")
print(f"Total samples: ", len(df))
df.head()

Total samples:  1120

                                        text_feature
0  Address: ΤΡΑΠΕΖΟΥΝΤΟΣ 25, Zip Code: 38445, Cit...
1  Address: 6ο ΧΛΜ ΒΟΛΟΥ - ΛΑΡΙΣΑΣ, Zip Code: 385...
2  Address: 1χλμ ΒΟΛΟΥ - ΔΙΜΗΝΙΟΥ, Zip Code: 3833...
3  Address: 4χιλ ΠΕΟ  ΒΟΛΟΥ-ΛΑΡΙΣΗΣ, Zip Code: 38...
4  Address: ΔΙΜΗΝΙ ΘΕΣΗ ΤΟΥΜΠΑ, Zip Code: 38500, ...

In [ ]:
results = []

# predict each sample
for index, row in df.iterrows():

    # load LLM prompt
    text = row['text_feature']

    # get LLM prediction
    result = classifier(text, candidate_labels)

    # Store results
    results.append({
        'text': text,
        'success_probability': result['scores'][result['labels'].index("success")] if "success" in result['labels'] else None
    })

In [ ]:
results_df = pd.DataFrame(results)
results_df.head()

                                                text  success_probability
0  Address: ΤΡΑΠΕΖΟΥΝΤΟΣ 25, Zip Code: 38445, Cit...             0.736039
1  Address: 6ο ΧΛΜ ΒΟΛΟΥ - ΛΑΡΙΣΑΣ, Zip Code: 385...             0.698067
2  Address: 1χλμ ΒΟΛΟΥ - ΔΙΜΗΝΙΟΥ, Zip Code: 3833...             0.780327
3  Address: 4χιλ ΠΕΟ  ΒΟΛΟΥ-ΛΑΡΙΣΗΣ, Zip Code: 38...             0.738734
4  Address: ΔΙΜΗΝΙ ΘΕΣΗ ΤΟΥΜΠΑ, Zip Code: 38500, ...             0.718420

In [ ]:
filename = f"LLM_prediction_{department}.csv"
results_df.to_csv(filename, index=False)
print(f"Saved {filename}")

Saved LLM_prediction_ΜΕΤΑΠΟΙΗΤΙΚΟ.csv

# ***LLM prediction: ΕΜΠΟΡΙΚΟ***

In [ ]:
department="ΕΜΠΟΡΙΚΟ"

In [ ]:
df = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/LLM_prompt_data/data_LLM_" +department +".csv")
print(f"Total samples: ", len(df))
df.head()

Total samples:  5206

                                        text_feature
0  Address: Γ. ΙΜΒΡΙΩΤΗ 7, Zip Code: 38500, City:...
1  Address: ΑΛΕΞΑΝΔΡΑΣ 177, Zip Code: 38221, City...
2  Address: ΜΑΙΑΝΔΡΟΥ 21, Zip Code: 38445, City: ...
3  Address: ΛΕΩΦΟΡΟΣ ΕΙΡΗΝΗΣ - ΔΟΡΥΛΑΙΟΥ, Zip Cod...
4  Address: ΙΑΣΟΝΟΣ - ΑΓΙΟΥ ΝΙΚΟΛΑΟΥ, Zip Code: 3...

In [ ]:
results = []

# predict each sample
for index, row in df.iterrows():

    # load LLM prompt
    text = row['text_feature']

    # get LLM prediction
    result = classifier(text, candidate_labels)

    # Store results
    results.append({
        'text': text,
        'success_probability': result['scores'][result['labels'].index("success")] if "success" in result['labels'] else None
    })

In [ ]:
results_df = pd.DataFrame(results)
results_df.head()

                                                text  success_probability
0  Address: Γ. ΙΜΒΡΙΩΤΗ 7, Zip Code: 38500, City:...             0.651447
1  Address: ΑΛΕΞΑΝΔΡΑΣ 177, Zip Code: 38221, City...             0.741244
2  Address: ΜΑΙΑΝΔΡΟΥ 21, Zip Code: 38445, City: ...             0.755309
3  Address: ΛΕΩΦΟΡΟΣ ΕΙΡΗΝΗΣ - ΔΟΡΥΛΑΙΟΥ, Zip Cod...             0.701264
4  Address: ΙΑΣΟΝΟΣ - ΑΓΙΟΥ ΝΙΚΟΛΑΟΥ, Zip Code: 3...             0.710268

In [ ]:
filename = f"LLM_prediction_{department}.csv"
results_df.to_csv(filename, index=False)
print(f"Saved {filename}")

Saved LLM_prediction_ΕΜΠΟΡΙΚΟ.csv

# ***LLM prediction: ΥΠΗΡΕΣΙΩΝ***

In [26]:
department="ΥΠΗΡΕΣΙΩΝ"

In [27]:
df = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/LLM_prompt_data/data_LLM_" +department +".csv")
print(f"Total samples: ", len(df))
df.head()

Total samples:  6999

                                        text_feature
0  Address: 2ας ΝΟΕΜΒΡΙΟΥ - ΞΕΝΟΦΩΝΤΟΣ, Zip Code:...
1  Address: ΝΙΚΟΤΣΑΡΑ 44, Zip Code: 38221, City: ...
2  Address: ΦΙΛΑΡΕΤΟΥ 6, Zip Code: 38333, City: Β...
3  Address: ΠΗΛΙΟΥ 37, Zip Code: 38333, City: ΒΟΛ...
4  Address: Π. ΜΕΛΑ 65Α, Zip Code: 38333, City: Β...

In [28]:
results = []

# predict each sample
for index, row in df.iterrows():

    # load LLM prompt
    text = row['text_feature']

    # get LLM prediction
    result = classifier(text, candidate_labels)

    # Store results
    results.append({
        'text': text,
        'success_probability': result['scores'][result['labels'].index("success")] if "success" in result['labels'] else None
    })

NameError: name 'classifier' is not defined

In [ ]:
results_df = pd.DataFrame(results)
results_df.head()

In [ ]:
filename = f"LLM_prediction_{department}.csv"
results_df.to_csv(filename, index=False)
print(f"Saved {filename}")

# ***fine-tune attempt***

## Model Class

In [34]:
import torch
from transformers import BartForSequenceClassification

class BartForProbabilityRegression(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.model = BartForSequenceClassification.from_pretrained("facebook/bart-large-mnli", num_labels=1, ignore_mismatched_sizes=True)
        self.model.classifier = torch.nn.Linear(self.model.config.hidden_size, 1)  # Single neuron for regression
        self.sigmoid = torch.nn.Sigmoid()  # Ensure output is in [0,1]
        self.loss_fn = torch.nn.MSELoss()

    def forward(self, input_ids, attention_mask, labels=None):
        outputs = self.model(input_ids, attention_mask=attention_mask)
        logits = self.model.classifier(outputs[0])  # Linear layer output
        probability = self.sigmoid(logits)  # Apply sigmoid to keep in [0,1]

        loss = None
        if labels is not None:
            loss = self.loss_fn(probability.squeeze(-1), labels.float())  # Ensure correct shape

        return {"loss": loss, "logits": probability}

## Load the data

In [9]:
departments = ['ΥΠΗΡΕΣΙΩΝ', 'ΕΜΠΟΡΙΚΟ', 'ΜΕΤΑΠΟΙΗΤΙΚΟ', 'ΤΟΥΡΙΣΤΙΚΟ']

In [18]:
fine_tuning_dfs = []

for department in departments:

    # load llm prompts
    llm_df = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/LLM_prompt_data/data_LLM_" + department + ".csv")

    # load real data
    exel_df = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/Success Probability - Real/data_" + department + ".csv")
    exel_df = exel_df[['active years scaled']]

    # make llm df
    fine_tuning_df = llm_df[['text_feature']].rename(columns={'text_feature': 'text'})
    fine_tuning_df['labels'] = exel_df['active years scaled']
    fine_tuning_dfs.append(fine_tuning_df)
    print(fine_tuning_df.head())

                                                text    labels
0  Address: 2ας ΝΟΕΜΒΡΙΟΥ - ΞΕΝΟΦΩΝΤΟΣ, Zip Code:...  0.498995
1  Address: ΝΙΚΟΤΣΑΡΑ 44, Zip Code: 38221, City: ...  0.404230
2  Address: ΦΙΛΑΡΕΤΟΥ 6, Zip Code: 38333, City: Β...  0.138712
3  Address: ΠΗΛΙΟΥ 37, Zip Code: 38333, City: ΒΟΛ...  0.180561
4  Address: Π. ΜΕΛΑ 65Α, Zip Code: 38333, City: Β...  0.203846
                                                text    labels
0  Address: Γ. ΙΜΒΡΙΩΤΗ 7, Zip Code: 38500, City:...  0.276112
1  Address: ΑΛΕΞΑΝΔΡΑΣ 177, Zip Code: 38221, City...  0.278892
2  Address: ΜΑΙΑΝΔΡΟΥ 21, Zip Code: 38445, City: ...  0.164251
3  Address: ΛΕΩΦΟΡΟΣ ΕΙΡΗΝΗΣ - ΔΟΡΥΛΑΙΟΥ, Zip Cod...  0.137505
4  Address: ΙΑΣΟΝΟΣ - ΑΓΙΟΥ ΝΙΚΟΛΑΟΥ, Zip Code: 3...  0.128957
                                                text    labels
0  Address: ΤΡΑΠΕΖΟΥΝΤΟΣ 25, Zip Code: 38445, Cit...  0.123608
1  Address: 6ο ΧΛΜ ΒΟΛΟΥ - ΛΑΡΙΣΑΣ, Zip Code: 385...  0.389966
2  Address: 1χλμ ΒΟΛΟΥ - ΔΙΜΗΝΙΟΥ, Zip Code: 3833...  0.512473
3  Address: 4χιλ ΠΕΟ  ΒΟΛΟΥ-ΛΑΡΙΣΗΣ, Zip Code: 38...  0.471882
4  Address: ΔΙΜΗΝΙ ΘΕΣΗ ΤΟΥΜΠΑ, Zip Code: 38500, ...  0.029473
                                                text    labels
0  Address: Γ. ΣΙΑΦΛΕΚΗ 8, Zip Code: 38222, City:...  0.137715
1  Address: 28ΗΣ ΟΚΤΩΒΡΙΟΥ 155 - ΣΠ. ΣΠΥΡΙΔΗ, Zip...  0.643108
2  Address: Σ. ΣΠΥΡΙΔΗ 96, Zip Code: 38221, City:...  0.083384
3  Address: ΒΕΝΙΖΕΛΟΥ 67, Zip Code: 38221, City: ...  0.835941
4  Address: ΚΥΠΡΟΥ 5Δ, Zip Code: 38221, City: ΒΟΛ...  0.580754

In [19]:
from sklearn.model_selection import train_test_split

final_train_df = pd.DataFrame()
final_test_df = pd.DataFrame()

for df in fine_tuning_dfs:

    # slplit the df
    train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

    # concat the dfs
    final_train_df = pd.concat([final_train_df, train_df], ignore_index=True)
    final_test_df = pd.concat([final_test_df, test_df], ignore_index=True)

print("Final Training Data:")
print(final_train_df.head())
print("Final Test Data:")
print(final_test_df.head())

Final Training Data:
                                                text    labels
0  Address: ΕΛ. ΒΕΝΙΖΕΛΟΥ  43, Zip Code: 38221, C...  0.483000
1  Address: ΔΙΜΗΝΙ, Zip Code: 38500, City: ΒΟΛΟΣ,...  0.611538
2  Address: ΧΑΤΖΗΒΑΣΙΛΗ 14, Zip Code: 38333, City...  0.116528
3  Address: ΔΗΜΗΤΡΙΑΔΟΣ 190 - 192, Zip Code: 3822...  0.288331
4  Address: ΜΑΙΑΝΔΡΟΥ 51, Zip Code: 38446, City: ...  0.309571
Final Test Data:
                                                text    labels
0  Address: ΒΑΛΤΕΤΣΙΟΥ 13, Zip Code: 38334, City:...  0.446080
1  Address: Τ. ΟΙΚΟΝΟΜΑΚΗ 54 - ΔΟΝ ΔΑΛΕΖΙΟΥ, Zip ...  0.284818
2  Address: ΜΑΙΑΝΔΡΟΥ 89, Zip Code: 38446, City: ...  0.012534
3  Address: ΜΙΚΡΑΣΙΑΤΩΝ 67, Zip Code: 38333, City...  0.317437
4  Address: ΓΚΛΑΒΑΝΗ 96, Zip Code: 38221, City: Β...  0.000000

In [24]:
!pip install datasets

Collecting datasets
  Downloading datasets-3.4.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.10.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.13)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.4.1-py3-none-any.whl (487 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 487.4/487.4 kB 14.8 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 10.6 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 12.0 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 16.9 MB/s eta 0:00:00
Installing collected packages: xxhash, dill, multiprocess, datasets
Successfully installed datasets-3.4.1 dill-0.3.8 multiprocess-0.70.16 xxhash-3.5.0

In [25]:
from datasets import Dataset

dataset_train = Dataset.from_pandas(final_train_df)
dataset_test = Dataset.from_pandas(final_test_df)

## Load the model

In [29]:
# Tokenize text columns
def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

In [30]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-mnli")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [31]:
tokenized_train = dataset_train.map(tokenize_function, batched=True)
tokenized_test = dataset_test.map(tokenize_function, batched=True)

Map:   0%|          | 0/10773 [00:00<?, ? examples/s]

Map:   0%|          | 0/2695 [00:00<?, ? examples/s]

## Train the model

In [37]:
from transformers import Trainer, TrainingArguments

# Training arguments
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    evaluation_strategy="epoch",
)

/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

In [38]:
trainer = Trainer(
    model=BartForProbabilityRegression(),
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test
)

Some weights of BartForSequenceClassification were not initialized from the model checkpoint at facebook/bart-large-mnli and are newly initialized because the shapes did not match:
- classification_head.out_proj.bias: found shape torch.Size([3]) in the checkpoint and torch.Size([1]) in the model instantiated
- classification_head.out_proj.weight: found shape torch.Size([3, 1024]) in the checkpoint and torch.Size([1, 1024]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

OutOfMemoryError: CUDA out of memory. Tried to allocate 198.00 MiB. GPU 0 has a total capacity of 14.74 GiB of which 2.12 MiB is free. Process 3101 has 14.74 GiB memory in use. Of the allocated memory 14.49 GiB is allocated by PyTorch, and 127.36 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [36]:
trainer.train()

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: giwrgoskakepakis (giwrgoskakepakis-university-of-thessally) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacity of 14.74 GiB of which 2.12 MiB is free. Process 3101 has 14.74 GiB memory in use. Of the allocated memory 14.49 GiB is allocated by PyTorch, and 127.36 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

## Evaluate the model