# **initials**

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# ***Department: ΥΠΗΡΕΣΙΩΝ***

In [3]:
department="ΥΠΗΡΕΣΙΩΝ"

In [4]:
df_real = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/Success Probability - Real/data_QGIS_" +department +".csv")
print(f"Total samples: ", len(df_real))
df_real.head()

Total samples:  6999

,full address,city,country,active years,active years scaled,successful
0,"2ας ΝΟΕΜΒΡΙΟΥ - ΞΕΝΟΦΩΝΤΟΣ, 38333",Volos,Greece,26.297057,0.498995,1
1,"ΝΙΚΟΤΣΑΡΑ 44, 38221",Volos,Greece,21.349760,0.404230,1
2,"ΦΙΛΑΡΕΤΟΥ 6, 38333",Volos,Greece,7.488022,0.138712,1
3,"ΠΗΛΙΟΥ 37, 38333",Volos,Greece,9.672827,0.180561,1
4,"Π. ΜΕΛΑ 65Α, 38333",Volos,Greece,10.888433,0.203846,1

In [5]:
df_pred = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/Success Probability - Predicted/LLM_prediction_" +department +".csv")
print(f"Total samples: ", len(df_pred))
df_pred.head()

Total samples:  6999

                                                text  success_probability
0  Address: 2ας ΝΟΕΜΒΡΙΟΥ - ΞΕΝΟΦΩΝΤΟΣ, Zip Code:...             0.721236
1  Address: ΝΙΚΟΤΣΑΡΑ 44, Zip Code: 38221, City: ...             0.751705
2  Address: ΦΙΛΑΡΕΤΟΥ 6, Zip Code: 38333, City: Β...             0.766852
3  Address: ΠΗΛΙΟΥ 37, Zip Code: 38333, City: ΒΟΛ...             0.747742
4  Address: Π. ΜΕΛΑ 65Α, Zip Code: 38333, City: Β...             0.685967

In [6]:
df_real['predicted success probability'] = df_pred['success_probability']
df_real.rename(columns={'active years scaled': 'real success probability'}, inplace=True)
df_real.to_csv(f'merged_data_' + department + '.csv', index=False)

# ***Department: ΕΜΠΟΡΙΚΟ***

In [7]:
department="ΕΜΠΟΡΙΚΟ"

In [8]:
df_real = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/Success Probability - Real/data_QGIS_" +department +".csv")
print(f"Total samples: ", len(df_real))
df_real.head()

Total samples:  5206

,full address,city,country,active years,active years scaled,successful
0,"Γ. ΙΜΒΡΙΩΤΗ 7, 38500",Volos,Greece,14.661191,0.276112,1
1,"ΑΛΕΞΑΝΔΡΑΣ 177, 38221",Volos,Greece,14.806297,0.278892,1
2,"ΜΑΙΑΝΔΡΟΥ 21, 38445",Volos,Greece,8.821355,0.164251,1
3,"ΛΕΩΦΟΡΟΣ ΕΙΡΗΝΗΣ - ΔΟΡΥΛΑΙΟΥ, 38445",Volos,Greece,7.425051,0.137505,1
4,"ΙΑΣΟΝΟΣ - ΑΓΙΟΥ ΝΙΚΟΛΑΟΥ, 38221",Volos,Greece,6.978782,0.128957,1

In [9]:
df_pred = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/Success Probability - Predicted/LLM_prediction_" +department +".csv")
print(f"Total samples: ", len(df_pred))
df_pred.head()

Total samples:  5206

                                                text  success_probability
0  Address: Γ. ΙΜΒΡΙΩΤΗ 7, Zip Code: 38500, City:...             0.651447
1  Address: ΑΛΕΞΑΝΔΡΑΣ 177, Zip Code: 38221, City...             0.741244
2  Address: ΜΑΙΑΝΔΡΟΥ 21, Zip Code: 38445, City: ...             0.755309
3  Address: ΛΕΩΦΟΡΟΣ ΕΙΡΗΝΗΣ - ΔΟΡΥΛΑΙΟΥ, Zip Cod...             0.701264
4  Address: ΙΑΣΟΝΟΣ - ΑΓΙΟΥ ΝΙΚΟΛΑΟΥ, Zip Code: 3...             0.710268

In [10]:
df_real['predicted success probability'] = df_pred['success_probability']
df_real.rename(columns={'active years scaled': 'real success probability'}, inplace=True)
df_real.to_csv(f'merged_data_' + department + '.csv', index=False)

# ***Department: ΜΕΤΑΠΟΙΗΤΙΚΟ***

In [11]:
department="ΜΕΤΑΠΟΙΗΤΙΚΟ"

In [12]:
df_real = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/Success Probability - Real/data_QGIS_" +department +".csv")
print(f"Total samples: ", len(df_real))
df_real.head()

Total samples:  1120

,full address,city,country,active years,active years scaled,successful
0,"ΤΡΑΠΕΖΟΥΝΤΟΣ 25, 38445",Volos,Greece,6.699521,0.123608,1
1,"6ο ΧΛΜ ΒΟΛΟΥ - ΛΑΡΙΣΑΣ, 38500",Volos,Greece,20.605065,0.389966,1
2,"1χλμ ΒΟΛΟΥ - ΔΙΜΗΝΙΟΥ, 38334",Volos,Greece,27.000684,0.512473,1
3,"4χιλ ΠΕΟ ΒΟΛΟΥ-ΛΑΡΙΣΗΣ, 38500",Volos,Greece,24.881588,0.471882,1
4,"ΔΙΜΗΝΙ ΘΕΣΗ ΤΟΥΜΠΑ, 38500",Volos,Greece,1.785079,0.029473,0

In [13]:
df_pred = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/Success Probability - Predicted/LLM_prediction_" +department +".csv")
print(f"Total samples: ", len(df_pred))
df_pred.head()

Total samples:  1120

                                                text  success_probability
0  Address: ΤΡΑΠΕΖΟΥΝΤΟΣ 25, Zip Code: 38445, Cit...             0.736039
1  Address: 6ο ΧΛΜ ΒΟΛΟΥ - ΛΑΡΙΣΑΣ, Zip Code: 385...             0.698067
2  Address: 1χλμ ΒΟΛΟΥ - ΔΙΜΗΝΙΟΥ, Zip Code: 3833...             0.780327
3  Address: 4χιλ ΠΕΟ  ΒΟΛΟΥ-ΛΑΡΙΣΗΣ, Zip Code: 38...             0.738734
4  Address: ΔΙΜΗΝΙ ΘΕΣΗ ΤΟΥΜΠΑ, Zip Code: 38500, ...             0.718420

In [14]:
df_real['predicted success probability'] = df_pred['success_probability']
df_real.rename(columns={'active years scaled': 'real success probability'}, inplace=True)
df_real.to_csv(f'merged_data_' + department + '.csv', index=False)

# ***Department: ΤΟΥΡΙΣΤΙΚΟ***

In [15]:
department="ΤΟΥΡΙΣΤΙΚΟ"

In [16]:
df_real = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/Success Probability - Real/data_QGIS_" +department +".csv")
print(f"Total samples: ", len(df_real))
df_real.head()

Total samples:  143

,full address,city,country,active years,active years scaled,successful
0,"Γ. ΣΙΑΦΛΕΚΗ 8, 38222",Volos,Greece,7.436003,0.137715,1
1,"28ΗΣ ΟΚΤΩΒΡΙΟΥ 155 - ΣΠ. ΣΠΥΡΙΔΗ, 38221",Volos,Greece,33.820671,0.643108,1
2,"Σ. ΣΠΥΡΙΔΗ 96, 38221",Volos,Greece,4.599589,0.083384,1
3,"ΒΕΝΙΖΕΛΟΥ 67, 38221",Volos,Greece,43.887748,0.835941,1
4,"ΚΥΠΡΟΥ 5Δ, 38221",Volos,Greece,30.565366,0.580754,1

In [17]:
df_pred = pd.read_csv(f"/content/drive/My Drive/Diplomatiki/Success Probability - Predicted/LLM_prediction_" +department +".csv")
print(f"Total samples: ", len(df_pred))
df_pred.head()

Total samples:  143

                                                text  success_probability
0  Address: Γ. ΣΙΑΦΛΕΚΗ 8, Zip Code: 38222, City:...             0.747190
1  Address: 28ΗΣ ΟΚΤΩΒΡΙΟΥ 155 - ΣΠ. ΣΠΥΡΙΔΗ, Zip...             0.689422
2  Address: Σ. ΣΠΥΡΙΔΗ 96, Zip Code: 38221, City:...             0.735422
3  Address: ΒΕΝΙΖΕΛΟΥ 67, Zip Code: 38221, City: ...             0.788468
4  Address: ΚΥΠΡΟΥ 5Δ, Zip Code: 38221, City: ΒΟΛ...             0.807303

In [18]:
df_real['predicted success probability'] = df_pred['success_probability']
df_real.rename(columns={'active years scaled': 'real success probability'}, inplace=True)
df_real.to_csv(f'merged_data_' + department + '.csv', index=False)