First of all, I will make 2 separate files that contain the 'Category' rows that will be used to create the Fine-Tuning and Inference datasets

## ***Initials***

In [1]:
import pandas as pd

## ***Load the Data***

In [13]:
df_main = pd.read_csv("C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\7. LLM - Fine Tuning\\1. Datasets Creation\\1. Synthetic Data Collection\\Extracted CSV Files\\Synthetic_Main_Categories.csv")
df_secondary = pd.read_csv("C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\7. LLM - Fine Tuning\\1. Datasets Creation\\1. Synthetic Data Collection\\Extracted CSV Files\\Synthetic_Secondary_Categories.csv")

## ***Create the Fine-Tuning Categories***

In [14]:
# ---- Output 1: Fine-tuning categories ----

# From main: take first 3 categories
main_finetune = df_main[['NACE', 'Description', 'Category1', 'Category2', 'Category3']].copy()
main_finetune.columns = ['NACE', 'Description', 'Category1', 'Category2', 'Category3']

# From secondary: already fine-tune style
secondary_finetune = df_secondary[['NACE', 'Description', 'Category1', 'Category2', 'Category3']].copy()

# Concatenate them
all_finetune = pd.concat([main_finetune, secondary_finetune], ignore_index=True)

In [15]:
print(all_finetune.shape)
all_finetune.head()

(306, 5)

,NACE,Description,Category1,Category2,Category3
0,86.22,Specialist medical practice activities,Healthcare Services,Specialized Medicine,Professional Health Services
1,56.10,Restaurants and mobile food service activities,Fast Food,Restaurant,Dining Experience
2,86.90,Other human health activities,Healthcare Services,Public Health,Wellness Services
3,56.30,Beverage serving activities,Cocktail Bar,Night Club,Bar
4,85.59,Other education n.e.c.,Language School,Tutoring center,Cram school

In [17]:
# Save fine-tuning file
all_finetune.to_csv('C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\7. LLM - Fine Tuning\\1. Datasets Creation\\1. Synthetic Data Collection\\Extracted CSV Files\\Categories_Fine_Tuning.csv', index=False)

## ***Create the Inference Categories***

In [21]:
main_inference = df_main[['NACE', 'Description', 'Category4', 'Category5', 'Category6']].copy()
main_inference.columns = ['NACE', 'Description', 'Category1', 'Category2', 'Category3']

In [22]:
print(main_inference.shape)
main_inference.head()

(53, 5)

,NACE,Description,Category1,Category2,Category3
0,86.22,Specialist medical practice activities,Patient Care,Medical Consulting,Clinical Expertise
1,56.10,Restaurants and mobile food service activities,Mexican Restaurant,Food Center,Grilled Meat Restaurant
2,86.90,Other human health activities,Community Care,Health Support,Preventive Care
3,56.30,Beverage serving activities,Cafe,Wine Bar,Beer Bar
4,85.59,Other education n.e.c.,Creative activities,Homework assistance,Social and emotional development

In [23]:
# Save inference file
main_inference.to_csv('C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\7. LLM - Fine Tuning\\1. Datasets Creation\\1. Synthetic Data Collection\\Extracted CSV Files\\Categories_Inference.csv', index=False)