## ***Initials***

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
import joblib

In [17]:
#base_path = "C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\6. Ground Truths\\1. Supervised Approach\\1. Approach 1\\"
base_path = "C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\6. Ground Truths\\1. Supervised Approach\\2. Approach 2 (won)\\"

## ***Load the Data***

In [18]:
df = pd.read_csv(f"{base_path}Extracted CSV Files\\ML_model_dataset.csv")

In [19]:
print(df.shape)
print(df.columns)
df.head()

(14688, 32)
Index(['NACE Code', 'Neighborhood', 'target', 'Municipal Community',
       'Centroid_x', 'Centroid_y', 'Neighborhood_Area_km2',
       'distance_to_volos_center_km', 'distance_to_volos_port_km',
       'dist_to_main_road_km', 'dist_to_bus_stop_km', 'dist_to_university_km',
       'ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ', 'ΔΗΜΟΣ', 'ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ', 'Population',
       'Άγαμοι_pct', 'Έγγαμοι_pct', 'Χήροι_pct', 'Διαζευγμένοι_pct',
       'age_0_14_pct', 'age_15_64_pct', 'age_65_plus_pct', 'low_education_pct',
       'medium_education_pct', 'high_education_pct', 'unemployment_rate',
       'labor_force_participation_rate', 'primary_sector_pct',
       'secondary_sector_pct', 'tertiary_sector_pct', 'Area_km2'],
      dtype='object')

,NACE Code,Neighborhood,target,Municipal Community,Centroid_x,Centroid_y,Neighborhood_Area_km2,distance_to_volos_center_km,distance_to_volos_port_km,dist_to_main_road_km,...,age_65_plus_pct,low_education_pct,medium_education_pct,high_education_pct,unemployment_rate,labor_force_participation_rate,primary_sector_pct,secondary_sector_pct,tertiary_sector_pct,Area_km2
0,47.76,Dimini,0,Δημοτική Κοινότητα Διμηνίου,22.882945,39.349112,37.344776,6.154015,5.418577,0.443434,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,47.76,Xrisi Akti Panagias,0,Δημοτική Κοινότητα Σέσκλου,22.836899,39.305430,9.983032,11.932475,11.015584,2.299921,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,47.76,Sesklo,0,Δημοτική Κοινότητα Σέσκλου,22.838168,39.353051,27.367312,9.814666,9.191001,0.482308,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,47.76,Agioi Anargiroi,0,Δημοτική Κοινότητα Βόλου,22.924059,39.366937,0.774436,2.296184,1.978856,0.058142,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,47.76,Aivaliotika,1,Δημοτική Κοινότητα Βόλου,22.922660,39.343696,4.848904,3.508166,2.529372,0.224486,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## ***Train the ML Model***

In [20]:
nace_encoder = LabelEncoder()
df['NACE_Code_Encoded'] = nace_encoder.fit_transform(df['NACE Code'])

In [21]:
# Step 1: Prepare feature set
non_feature_cols = ['NACE Code', 'Neighborhood', 'Municipal Community', 'ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ', 'ΔΗΜΟΣ', 'ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ', 'target']
feature_cols = [col for col in df.columns if col not in non_feature_cols]

X = df[feature_cols]
y = df['target']

In [22]:
# Step 2: Train the classifier
pipeline = Pipeline([
    ('scaler', MinMaxScaler()),
    ('clf', RandomForestClassifier(n_estimators=100, random_state=42))
])
pipeline.fit(X, y)

c:\Users\Giorgos\anaconda3\envs\machine-learning\lib\site-packages\sklearn\utils\_array_api.py:472: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmin(X, axis=axis))
c:\Users\Giorgos\anaconda3\envs\machine-learning\lib\site-packages\sklearn\utils\_array_api.py:489: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmax(X, axis=axis))

Pipeline(steps=[('scaler', MinMaxScaler()),
                ('clf', RandomForestClassifier(random_state=42))])

In [23]:
# Step 3: Predict probabilities for all rows (probability of class 1)
df['score'] = pipeline.predict_proba(X)[:, 1]

In [24]:
# Step 3: Predict probabilities for all rows (probability of class 1)
df['score'] = pipeline.predict_proba(X)[:, 1]

In [25]:
df.head()

,NACE Code,Neighborhood,target,Municipal Community,Centroid_x,Centroid_y,Neighborhood_Area_km2,distance_to_volos_center_km,distance_to_volos_port_km,dist_to_main_road_km,...,medium_education_pct,high_education_pct,unemployment_rate,labor_force_participation_rate,primary_sector_pct,secondary_sector_pct,tertiary_sector_pct,Area_km2,NACE_Code_Encoded,score
0,47.76,Dimini,0,Δημοτική Κοινότητα Διμηνίου,22.882945,39.349112,37.344776,6.154015,5.418577,0.443434,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179,0.02
1,47.76,Xrisi Akti Panagias,0,Δημοτική Κοινότητα Σέσκλου,22.836899,39.305430,9.983032,11.932475,11.015584,2.299921,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179,0.00
2,47.76,Sesklo,0,Δημοτική Κοινότητα Σέσκλου,22.838168,39.353051,27.367312,9.814666,9.191001,0.482308,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179,0.00
3,47.76,Agioi Anargiroi,0,Δημοτική Κοινότητα Βόλου,22.924059,39.366937,0.774436,2.296184,1.978856,0.058142,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179,0.04
4,47.76,Aivaliotika,1,Δημοτική Κοινότητα Βόλου,22.922660,39.343696,4.848904,3.508166,2.529372,0.224486,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179,0.57

## ***Save the Data with the ML Model Predictions***

In [26]:
df.to_csv(f"{base_path}Extracted CSV Files\\ML_model_dataset_with_score.csv", index=False)

## ***Save the ML Model***

In [27]:
# Save the model pipeline (scaler + classifier)
joblib.dump(pipeline, f"{base_path}ML Model\\random_forest.pkl")

# Save the LabelEncoder for NACE codes
joblib.dump(nace_encoder, f"{base_path}ML Model\\nace_encoder.pkl")

['C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\6. Ground Truths\\1. Supervised Approach\\2. Approach 2 (won)\\ML Model\\nace_encoder.pkl']