## ***Initials***

In [2]:
import pandas as pd

## ***Load the Data***

In [3]:
neighborhood_df = pd.read_csv('C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\3. Base Datasets\\3. Data -  Smaller Spatial Units\\1. Neighborhoods\\Extracted CSV Files\\neighborhoods_enriched.csv')
neighborhood_df.drop(columns=['Neighborhood_Greek'], inplace=True)
print(neighborhood_df.shape)
print(neighborhood_df.columns)
neighborhood_df.head()

(48, 11)
Index(['Municipal Community', 'Neighborhood', 'Centroid_x', 'Centroid_y',
       'Neighborhood_Area_km2', 'Geometry', 'distance_to_volos_center_km',
       'distance_to_volos_port_km', 'dist_to_main_road_km',
       'dist_to_bus_stop_km', 'dist_to_university_km'],
      dtype='object')

,Municipal Community,Neighborhood,Centroid_x,Centroid_y,Neighborhood_Area_km2,Geometry,distance_to_volos_center_km,distance_to_volos_port_km,dist_to_main_road_km,dist_to_bus_stop_km,dist_to_university_km
0,Municipal Community of Dimini,Dimini,22.882945,39.349112,37.344776,MULTIPOLYGON (((406692.718139543 4357521.85294...,6.154015,5.418577,0.443434,1.569912,4.273031
1,Municipal Community of Sesklos,Xrisi Akti Panagias,22.836899,39.305430,9.983032,MULTIPOLYGON (((396744.165394512 4351195.65810...,11.932475,11.015584,2.299921,2.410375,10.100771
2,Municipal Community of Sesklos,Sesklo,22.838168,39.353051,27.367312,MULTIPOLYGON (((400839.361742302 4353031.79092...,9.814666,9.191001,0.482308,4.965561,7.989610
3,Municipal Community of Volos,Agioi Anargiroi,22.924059,39.366937,0.774436,MULTIPOLYGON (((406589.250339913 4357224.83344...,2.296184,1.978856,0.058142,0.063879,0.866021
4,Municipal Community of Volos,Aivaliotika,22.922660,39.343696,4.848904,MULTIPOLYGON (((407619.510540358 4356306.42684...,3.508166,2.529372,0.224486,0.246542,1.913456

In [4]:
municipal_community_df = pd.read_csv("C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\3. Base Datasets\\2. Data - Municipal Communities\\4. Exploratory Data Analysis\\Extracted CSV Files\\ELSTAT-demographic-economic.csv", index_col=0)
municipal_community_df.drop(columns=['ΔΗΜΟΤΙΚΗ ΚΟΙΝΟΤΗΤΑ ΕΛΛ'], inplace=True)
print(municipal_community_df.shape)
print(municipal_community_df.columns)
municipal_community_df.head()

(76, 21)
Index(['ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ', 'ΔΗΜΟΣ', 'ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ',
       'ΔΗΜΟΤΙΚΗ ΚΟΙΝΟΤΗΤΑ', 'Population', 'Άγαμοι_pct', 'Έγγαμοι_pct',
       'Χήροι_pct', 'Διαζευγμένοι_pct', 'age_0_14_pct', 'age_15_64_pct',
       'age_65_plus_pct', 'low_education_pct', 'medium_education_pct',
       'high_education_pct', 'unemployment_rate',
       'labor_force_participation_rate', 'primary_sector_pct',
       'secondary_sector_pct', 'tertiary_sector_pct', 'Area_km2'],
      dtype='object')

,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ,ΔΗΜΟΣ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ,ΔΗΜΟΤΙΚΗ ΚΟΙΝΟΤΗΤΑ,Population,Άγαμοι_pct,Έγγαμοι_pct,Χήροι_pct,Διαζευγμένοι_pct,age_0_14_pct,...,age_65_plus_pct,low_education_pct,medium_education_pct,high_education_pct,unemployment_rate,labor_force_participation_rate,primary_sector_pct,secondary_sector_pct,tertiary_sector_pct,Area_km2
0,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΒΟΛΟΥ,Municipal Community of Volos,85806,0.4032,0.4630,0.0809,0.0528,0.1300,...,0.2221,0.3634,0.3663,0.2704,0.1545,0.4188,0.0313,0.1666,0.8022,26.790807
1,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΓΡΙΑΣ,Municipal Community of Agria,4926,0.3577,0.5173,0.0796,0.0461,0.1407,...,0.2359,0.4670,0.3341,0.1987,0.1555,0.3955,0.0816,0.1864,0.7314,3.737347
2,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΓΡΙΑΣ,Municipal Community of Drakeia,369,0.3496,0.4580,0.1382,0.0325,0.1274,...,0.2873,0.6667,0.2493,0.0840,0.1439,0.3767,0.4545,0.0826,0.4628,21.683415
3,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΙΣΩΝΙΑΣ,Municipal Community of Dimini,2101,0.3889,0.5007,0.0776,0.0343,0.1480,...,0.2080,0.5437,0.3163,0.1395,0.2211,0.4327,0.1161,0.2365,0.6459,37.323451
4,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΙΣΩΝΙΑΣ,Municipal Community of Sesklos,899,0.3960,0.5184,0.0645,0.0234,0.1769,...,0.2147,0.6009,0.2812,0.1179,0.1304,0.3838,0.1424,0.3609,0.4967,37.329725

## ***Merge: Neighborhoods with Municipal Communties***

In [5]:
# Perform the merge
community_df_renamed = municipal_community_df.rename(columns={'ΔΗΜΟΤΙΚΗ ΚΟΙΝΟΤΗΤΑ': 'Municipal Community'})

neighborhood_ELSTAT_df = pd.merge(
    neighborhood_df,
    community_df_renamed,
    on='Municipal Community',
    how='left'
)

print(neighborhood_ELSTAT_df.shape)
print(neighborhood_ELSTAT_df.columns)
neighborhood_ELSTAT_df.head()

(48, 31)
Index(['Municipal Community', 'Neighborhood', 'Centroid_x', 'Centroid_y',
       'Neighborhood_Area_km2', 'Geometry', 'distance_to_volos_center_km',
       'distance_to_volos_port_km', 'dist_to_main_road_km',
       'dist_to_bus_stop_km', 'dist_to_university_km', 'ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ',
       'ΔΗΜΟΣ', 'ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ', 'Population', 'Άγαμοι_pct', 'Έγγαμοι_pct',
       'Χήροι_pct', 'Διαζευγμένοι_pct', 'age_0_14_pct', 'age_15_64_pct',
       'age_65_plus_pct', 'low_education_pct', 'medium_education_pct',
       'high_education_pct', 'unemployment_rate',
       'labor_force_participation_rate', 'primary_sector_pct',
       'secondary_sector_pct', 'tertiary_sector_pct', 'Area_km2'],
      dtype='object')

,Municipal Community,Neighborhood,Centroid_x,Centroid_y,Neighborhood_Area_km2,Geometry,distance_to_volos_center_km,distance_to_volos_port_km,dist_to_main_road_km,dist_to_bus_stop_km,...,age_65_plus_pct,low_education_pct,medium_education_pct,high_education_pct,unemployment_rate,labor_force_participation_rate,primary_sector_pct,secondary_sector_pct,tertiary_sector_pct,Area_km2
0,Municipal Community of Dimini,Dimini,22.882945,39.349112,37.344776,MULTIPOLYGON (((406692.718139543 4357521.85294...,6.154015,5.418577,0.443434,1.569912,...,0.2080,0.5437,0.3163,0.1395,0.2211,0.4327,0.1161,0.2365,0.6459,37.323451
1,Municipal Community of Sesklos,Xrisi Akti Panagias,22.836899,39.305430,9.983032,MULTIPOLYGON (((396744.165394512 4351195.65810...,11.932475,11.015584,2.299921,2.410375,...,0.2147,0.6009,0.2812,0.1179,0.1304,0.3838,0.1424,0.3609,0.4967,37.329725
2,Municipal Community of Sesklos,Sesklo,22.838168,39.353051,27.367312,MULTIPOLYGON (((400839.361742302 4353031.79092...,9.814666,9.191001,0.482308,4.965561,...,0.2147,0.6009,0.2812,0.1179,0.1304,0.3838,0.1424,0.3609,0.4967,37.329725
3,Municipal Community of Volos,Agioi Anargiroi,22.924059,39.366937,0.774436,MULTIPOLYGON (((406589.250339913 4357224.83344...,2.296184,1.978856,0.058142,0.063879,...,0.2221,0.3634,0.3663,0.2704,0.1545,0.4188,0.0313,0.1666,0.8022,26.790807
4,Municipal Community of Volos,Aivaliotika,22.922660,39.343696,4.848904,MULTIPOLYGON (((407619.510540358 4356306.42684...,3.508166,2.529372,0.224486,0.246542,...,0.2221,0.3634,0.3663,0.2704,0.1545,0.4188,0.0313,0.1666,0.8022,26.790807

## ***Save the Data***

In [ ]:
neighborhood_ELSTAT_df.to_csv("C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\4. Joining Datasets\\4. Joining Neighborhood - Municipal Community Data\\Extracted CSV Files\\neighborhood_ELSTAT.csv")