This file attempts to merge the different datasets. So far i already have processed 3 datastes (forthsquare, xrysos odigos, greek catalog) in order to be able to be merged, and i will attempt to combine them first. Later i may add more.

# ***Forsquare - Xrysos Odigos - Greek Catalog***

## ***Initials***

In [1]:
import pandas as pd

## ***Load the Data***

In [18]:
df1 = pd.read_csv("API Calls/Fourthsquare/forthsquare_data.csv")
df2 = pd.read_csv("Web Scraping/Χρυσός Οδηγός/xrysos-odigos-volos-ratings.csv")
df3 = pd.read_csv("Web Scraping/Greek Catalog/greek-catalog-volos.csv")

df1['Source'] = 'foursquare'
df2['Source'] = 'xrysos odigos'
df3['Source'] = 'greek catalog'

In [19]:
df1.drop(columns=['category_id'], inplace=True)
df1.head()

,name,category_name,lat,long,address,country,city,postal_code,rating,reviews,Source
0,Άνθη-φυτά,Flower Store,39.335293,22.923506,6χλ.βολου,Greece,Βόλος,383 34,NaN,NaN,foursquare
1,Μέταλλο και ξύλο,Furniture and Home Store,39.339233,22.923969,NaN,Greece,NaN,383 34,NaN,NaN,foursquare
2,Προφήτης Ηλίας Αλυκών,Church,39.332305,22.926496,NaN,Greece,Βόλος,383 34,NaN,NaN,foursquare
3,Frago Cargo (Φραγγοσ Νικολαοσ),"Shipping, Freight, and Material Transportation...",39.332756,22.929457,Αλόης 179Γ,Greece,Βόλος,383 34,NaN,NaN,foursquare
4,Αλφα Ωμεγα Express Market,Grocery Store,39.332876,22.929374,Βάκχου 4,Greece,Βόλος,383 34,NaN,NaN,foursquare

In [12]:
df2.head()

,category,businessName,description,rating,number_of_ratings,Address,City,ZIP,Latitude,Longitude,Country,Source
0,Ωχρά κηλίδα Βόλος,ΟΦΘΑΛΜΟΣ ΕΡΕΥΝΗΤΙΚΟ & ΟΦΘΑΛΜΟΛΟΓΙΚΟ ΙΝΣΤΙΤΟΥΤΟ,Το διαγνωστικό κέντρο ΟΦΘΑΛΜΟΣ ΕΡΕΥΝΗΤΙΚΟ & ΟΦ...,5,1.0,Λεωφόρος Δήμαρχου Άγγελου Μεταξά 13,Γλυφάδα Αττικής,166 75,37.863294,23.750630,Greece,xrysos odigos
1,Ωχρά κηλίδα Βόλος,ΖΗΣΟΥΛΗΣ ΙΩΑΝΝΗΣ,Ο Dr ΖΗΣΟΥΛΗΣ ΙΩΑΝΝΗΣ ΑΙΜ είναι Χειρουργός Οφθ...,NaN,NaN,"Ασκληπιού 38 & Μανδηλαρά, Κέντρο",Λάρισα Λάρισας,412 22,39.635192,22.418178,Greece,xrysos odigos
2,Ωχρά κηλίδα Βόλος,ΤΖΙΤΖΑΣ ΠΑΝΑΓΙΩΤΗΣ,Ο ΤΖΙΤΖΑΣ ΠΑΝΑΓΙΩΤΗΣ είναι οφθαλμίατρος με ιατ...,NaN,NaN,"Τοπάλη Κωνσταντίνου 56, Κύματα",Βόλος Μαγνησίας,382 21,NaN,NaN,Greece,xrysos odigos
3,Ωχρά κηλίδα Βόλος,ΝΤΟΚΟΣ ΑΘΑΝΑΣΙΟΣ,Το ιατρείο του Χειρουργού Οφθαλμίατρου Ντόκου ...,5,1.0,Ιωλκού 270,Βόλος Μαγνησίας,382 21,39.375641,22.959328,Greece,xrysos odigos
4,Ωχρά κηλίδα Βόλος,ΒΑΪΟΠΟΥΛΟΥ ΑΡΕΤΗ,"Η ιατρός Βαϊοπούλου Αρετή, χειρουργός οφθαλμία...",NaN,NaN,"Τοπάλη 84, Κέντρο",Βόλος Μαγνησίας,382 21,39.362073,22.948824,Greece,xrysos odigos

In [13]:
df3.head()

,name,number_of_ratings,rating,category,Address,City,ZIP,Latitude,Longitude,Country,Source
0,ΕΣΤΙΑΤΟΡΙΟ-ΜΕΖΕΔΟΠΩΛΕΙΟ | ΠΑΛΙΑ ΒΟΛΟΣ ΜΑΓΝΗΣΙΑ...,0,0.0,Εστιατόρια,Κροκίου 30,Βόλος,38334,39.361927,22.935708,Greece,greek catalog
1,ΠΛΑΣΤΙΚΕΣ ΠΑΛΕΤΕΣ-ΚΙΒΩΤΙΑ-ΤΕΛΑΡΑ | ΤΣΙΜΠΟΥΚΗΣ,0,0.0,Εμπόριο Κατασκευή Παλετών,28ης Οκτωβρίου 207,Βόλος,38221,39.359166,22.953138,Greece,greek catalog
2,ΑΡΧΙΤΕΚΤΟΝΙΚΟ ΓΡΑΦΕΙΟ ΒΟΛΟΣ | ONMA DESIGN STUDIO,0,0.0,Τεχνικοί-Υπηρεσίες-Επισκευές,Χατζηαργύρη 80,Βόλος,38333,39.365274,22.947753,Greece,greek catalog
3,ΔΙΚΗΓΟΡΙΚΟ ΓΡΑΦΕΙΟ ΒΟΛΟΣ | ΠΑΠΑΘΑΝΑΣΙΟΥ ΠΗΝΕΛΟΠΗ,1,5.0,Δικηγόροι-Δικηγορικά Γραφεία,Άνθιμου Γαζή 128,Βόλος,38221,39.362892,22.949781,Greece,greek catalog
4,ΝΕΥΡΟΛΟΓΟΣ ΒΟΛΟΣ | ΚΑΛΟΧΡΙΣΤΙΑΝΑΚΗΣ ΔΗΜΗΤΡΙΟΣ,0,0.0,Γιατροί,"Σπυρίδη Σπύρου 3, 6ος όροφος",Βόλος,38221,39.359336,22.947108,Greece,greek catalog

## ***Rename Columns***

We need to assign the same names to the corresponding colunms in order to merge the 3 dfs

In [23]:
df1 = df1.rename(columns={
    'name': 'Name',
    'category_name': 'Category',
    'lat': 'Latitude',
    'long': 'Longitude',
    'postal_code': 'ZIP',
    'address': 'Address',
    'country': 'Country',
    'city': 'City',
    'rating' : 'Rating',
    'reviews' : 'Reviews',
    'ZIP' : 'Postal Code',
})

df1.head()

,Name,Category,Latitude,Longitude,Address,Country,City,Postal Code,Rating,Reviews,Source
0,Άνθη-φυτά,Flower Store,39.335293,22.923506,6χλ.βολου,Greece,Βόλος,383 34,NaN,NaN,foursquare
1,Μέταλλο και ξύλο,Furniture and Home Store,39.339233,22.923969,NaN,Greece,NaN,383 34,NaN,NaN,foursquare
2,Προφήτης Ηλίας Αλυκών,Church,39.332305,22.926496,NaN,Greece,Βόλος,383 34,NaN,NaN,foursquare
3,Frago Cargo (Φραγγοσ Νικολαοσ),"Shipping, Freight, and Material Transportation...",39.332756,22.929457,Αλόης 179Γ,Greece,Βόλος,383 34,NaN,NaN,foursquare
4,Αλφα Ωμεγα Express Market,Grocery Store,39.332876,22.929374,Βάκχου 4,Greece,Βόλος,383 34,NaN,NaN,foursquare

In [25]:
df2 = df2.rename(columns={
    'businessName': 'Name',
    'category': 'Category',
    'number_of_ratings': 'Number_of_ratings',
    'rating': 'Rating',
    'Number_of_ratings': 'Reviews',
    'ZIP' : 'Postal Code',
    'description': 'Description',
})

df2.head()

,Category,Name,Description,Rating,Reviews,Address,City,Postal Code,Latitude,Longitude,Country,Source
0,Ωχρά κηλίδα Βόλος,ΟΦΘΑΛΜΟΣ ΕΡΕΥΝΗΤΙΚΟ & ΟΦΘΑΛΜΟΛΟΓΙΚΟ ΙΝΣΤΙΤΟΥΤΟ,Το διαγνωστικό κέντρο ΟΦΘΑΛΜΟΣ ΕΡΕΥΝΗΤΙΚΟ & ΟΦ...,5,1.0,Λεωφόρος Δήμαρχου Άγγελου Μεταξά 13,Γλυφάδα Αττικής,166 75,37.863294,23.750630,Greece,xrysos odigos
1,Ωχρά κηλίδα Βόλος,ΖΗΣΟΥΛΗΣ ΙΩΑΝΝΗΣ,Ο Dr ΖΗΣΟΥΛΗΣ ΙΩΑΝΝΗΣ ΑΙΜ είναι Χειρουργός Οφθ...,NaN,NaN,"Ασκληπιού 38 & Μανδηλαρά, Κέντρο",Λάρισα Λάρισας,412 22,39.635192,22.418178,Greece,xrysos odigos
2,Ωχρά κηλίδα Βόλος,ΤΖΙΤΖΑΣ ΠΑΝΑΓΙΩΤΗΣ,Ο ΤΖΙΤΖΑΣ ΠΑΝΑΓΙΩΤΗΣ είναι οφθαλμίατρος με ιατ...,NaN,NaN,"Τοπάλη Κωνσταντίνου 56, Κύματα",Βόλος Μαγνησίας,382 21,NaN,NaN,Greece,xrysos odigos
3,Ωχρά κηλίδα Βόλος,ΝΤΟΚΟΣ ΑΘΑΝΑΣΙΟΣ,Το ιατρείο του Χειρουργού Οφθαλμίατρου Ντόκου ...,5,1.0,Ιωλκού 270,Βόλος Μαγνησίας,382 21,39.375641,22.959328,Greece,xrysos odigos
4,Ωχρά κηλίδα Βόλος,ΒΑΪΟΠΟΥΛΟΥ ΑΡΕΤΗ,"Η ιατρός Βαϊοπούλου Αρετή, χειρουργός οφθαλμία...",NaN,NaN,"Τοπάλη 84, Κέντρο",Βόλος Μαγνησίας,382 21,39.362073,22.948824,Greece,xrysos odigos

In [28]:
df3 = df3.rename(columns={
    'name': 'Name',
    'category': 'Category',
    'number_of_ratings': 'Reviews',
    'rating' : 'Rating',
    'ZIP' : 'Postal Code',
})

df3.head()

,Name,Reviews,Rating,Category,Address,City,Postal Code,Latitude,Longitude,Country,Source
0,ΕΣΤΙΑΤΟΡΙΟ-ΜΕΖΕΔΟΠΩΛΕΙΟ | ΠΑΛΙΑ ΒΟΛΟΣ ΜΑΓΝΗΣΙΑ...,0,0.0,Εστιατόρια,Κροκίου 30,Βόλος,38334,39.361927,22.935708,Greece,greek catalog
1,ΠΛΑΣΤΙΚΕΣ ΠΑΛΕΤΕΣ-ΚΙΒΩΤΙΑ-ΤΕΛΑΡΑ | ΤΣΙΜΠΟΥΚΗΣ,0,0.0,Εμπόριο Κατασκευή Παλετών,28ης Οκτωβρίου 207,Βόλος,38221,39.359166,22.953138,Greece,greek catalog
2,ΑΡΧΙΤΕΚΤΟΝΙΚΟ ΓΡΑΦΕΙΟ ΒΟΛΟΣ | ONMA DESIGN STUDIO,0,0.0,Τεχνικοί-Υπηρεσίες-Επισκευές,Χατζηαργύρη 80,Βόλος,38333,39.365274,22.947753,Greece,greek catalog
3,ΔΙΚΗΓΟΡΙΚΟ ΓΡΑΦΕΙΟ ΒΟΛΟΣ | ΠΑΠΑΘΑΝΑΣΙΟΥ ΠΗΝΕΛΟΠΗ,1,5.0,Δικηγόροι-Δικηγορικά Γραφεία,Άνθιμου Γαζή 128,Βόλος,38221,39.362892,22.949781,Greece,greek catalog
4,ΝΕΥΡΟΛΟΓΟΣ ΒΟΛΟΣ | ΚΑΛΟΧΡΙΣΤΙΑΝΑΚΗΣ ΔΗΜΗΤΡΙΟΣ,0,0.0,Γιατροί,"Σπυρίδη Σπύρου 3, 6ος όροφος",Βόλος,38221,39.359336,22.947108,Greece,greek catalog

In [ ]:
# Ensure ZIP codes are string type to preserve leading zeros
for df in [df1, df2, df3]:
    df['Postal Code'] = df['Postal Code'].astype(str).str.strip()

## ***Merge the Data***

In [31]:
combined_df = pd.concat([df1, df2, df3], ignore_index=True)

In [32]:
combined_df.head()

,Name,Category,Latitude,Longitude,Address,Country,City,Postal Code,Rating,Reviews,Source,Description
0,Άνθη-φυτά,Flower Store,39.335293,22.923506,6χλ.βολου,Greece,Βόλος,383 34,NaN,NaN,foursquare,NaN
1,Μέταλλο και ξύλο,Furniture and Home Store,39.339233,22.923969,NaN,Greece,NaN,383 34,NaN,NaN,foursquare,NaN
2,Προφήτης Ηλίας Αλυκών,Church,39.332305,22.926496,NaN,Greece,Βόλος,383 34,NaN,NaN,foursquare,NaN
3,Frago Cargo (Φραγγοσ Νικολαοσ),"Shipping, Freight, and Material Transportation...",39.332756,22.929457,Αλόης 179Γ,Greece,Βόλος,383 34,NaN,NaN,foursquare,NaN
4,Αλφα Ωμεγα Express Market,Grocery Store,39.332876,22.929374,Βάκχου 4,Greece,Βόλος,383 34,NaN,NaN,foursquare,NaN

## ***Save the Data***

In [33]:
combined_df.to_csv("forsquare_xrysosOdigos_greekCatalog.csv", index=False)

In [36]:
print(f"Lengths: {len(df1)} + {len(df2)} + {len(df3)} = {len(df1) + len(df2) + len(df3)}")
print(len(combined_df))

Lengths: 307 + 4364 + 46 = 4717
4717

# ***Vacation Renter***

## ***Load the Data***

In [12]:
df123 = pd.read_csv("forsquare_xrysosOdigos_greekCatalog.csv")
df4 = pd.read_csv("Web Scraping/Vacation Renter/vacation-renter-volos.csv")

df4['Source'] = 'vacation renter'

In [13]:
df123.head()

,Name,Category,Latitude,Longitude,Address,Country,City,Postal Code,Rating,Reviews,Source,Description
0,Άνθη-φυτά,Flower Store,39.335293,22.923506,6χλ.βολου,Greece,Βόλος,383 34,NaN,NaN,foursquare,NaN
1,Μέταλλο και ξύλο,Furniture and Home Store,39.339233,22.923969,NaN,Greece,NaN,383 34,NaN,NaN,foursquare,NaN
2,Προφήτης Ηλίας Αλυκών,Church,39.332305,22.926496,NaN,Greece,Βόλος,383 34,NaN,NaN,foursquare,NaN
3,Frago Cargo (Φραγγοσ Νικολαοσ),"Shipping, Freight, and Material Transportation...",39.332756,22.929457,Αλόης 179Γ,Greece,Βόλος,383 34,NaN,NaN,foursquare,NaN
4,Αλφα Ωμεγα Express Market,Grocery Store,39.332876,22.929374,Βάκχου 4,Greece,Βόλος,383 34,NaN,NaN,foursquare,NaN

In [14]:
df4.drop(columns=['features'], inplace=True)
df4.head()

,name,rating,description,Category,Country,Latitude,Longitude,Postal Code,Address,City,Source
0,IRIS COZY house,9.2,Comfortable Living Space: IRIS COZY house in V...,Hotel,Greece,39.369241,22.945422,38333,Βασσάνη 115Α,Βόλος,vacation renter
1,2nd Floor Apartment In Volos,8.0,Spacious Accommodations: 2nd Floor Apartment I...,Hotel,Greece,39.377589,22.914817,38445,15 Philadelphias 2nd Floor,Βόλος,vacation renter
2,Luxury Villa Thea,8.7,Elegant Accommodations: Luxury Villa Thea in V...,Hotel,Greece,39.362029,22.934405,38500,Grigoriou Lampraki 50,Βόλος,vacation renter
3,MAHE APARTMENT,9.1,Comfortable Living Space: MAHE APARTMENT in Vo...,Hotel,Greece,39.360689,22.947496,38221,35 Τοπάλη ΠΟΛΥΚΑΤΟΙΚΊΑ- 2οs οροφος,Βόλος,vacation renter
4,Charming Volos House 1,9.6,Spacious Accommodations: Charming Volos House ...,Hotel,Greece,39.361186,22.948707,38221,64 Σπυρίδη,Βόλος,vacation renter

## ***Rename Columns***

Again, we need to assign the same names to the corresponding colunms in order to merge the 2 dfs

In [15]:
df4 = df4.rename(columns={
    'name': 'Name',
    'rating' : 'Rating',
    'description': 'Description'
})

df4.head()

,Name,Rating,Description,Category,Country,Latitude,Longitude,Postal Code,Address,City,Source
0,IRIS COZY house,9.2,Comfortable Living Space: IRIS COZY house in V...,Hotel,Greece,39.369241,22.945422,38333,Βασσάνη 115Α,Βόλος,vacation renter
1,2nd Floor Apartment In Volos,8.0,Spacious Accommodations: 2nd Floor Apartment I...,Hotel,Greece,39.377589,22.914817,38445,15 Philadelphias 2nd Floor,Βόλος,vacation renter
2,Luxury Villa Thea,8.7,Elegant Accommodations: Luxury Villa Thea in V...,Hotel,Greece,39.362029,22.934405,38500,Grigoriou Lampraki 50,Βόλος,vacation renter
3,MAHE APARTMENT,9.1,Comfortable Living Space: MAHE APARTMENT in Vo...,Hotel,Greece,39.360689,22.947496,38221,35 Τοπάλη ΠΟΛΥΚΑΤΟΙΚΊΑ- 2οs οροφος,Βόλος,vacation renter
4,Charming Volos House 1,9.6,Spacious Accommodations: Charming Volos House ...,Hotel,Greece,39.361186,22.948707,38221,64 Σπυρίδη,Βόλος,vacation renter

## ***Merge the Data***

In [16]:
combined_df = pd.concat([df123, df4], ignore_index=True)

In [17]:
combined_df.head()

,Name,Category,Latitude,Longitude,Address,Country,City,Postal Code,Rating,Reviews,Source,Description
0,Άνθη-φυτά,Flower Store,39.335293,22.923506,6χλ.βολου,Greece,Βόλος,383 34,NaN,NaN,foursquare,NaN
1,Μέταλλο και ξύλο,Furniture and Home Store,39.339233,22.923969,NaN,Greece,NaN,383 34,NaN,NaN,foursquare,NaN
2,Προφήτης Ηλίας Αλυκών,Church,39.332305,22.926496,NaN,Greece,Βόλος,383 34,NaN,NaN,foursquare,NaN
3,Frago Cargo (Φραγγοσ Νικολαοσ),"Shipping, Freight, and Material Transportation...",39.332756,22.929457,Αλόης 179Γ,Greece,Βόλος,383 34,NaN,NaN,foursquare,NaN
4,Αλφα Ωμεγα Express Market,Grocery Store,39.332876,22.929374,Βάκχου 4,Greece,Βόλος,383 34,NaN,NaN,foursquare,NaN

In [18]:
print(f"Lengths: {len(df123)} + {len(df4)} = {len(df123) + len(df4)}")
print(len(combined_df))

Lengths: 4717 + 24 = 4741
4741

## ***Save the Data***

In [19]:
combined_df.to_csv("forsquare_xrysosOdigos_greekCatalog_vacationRenter.csv", index=False)