In [14]:
import pandas as pd
import folium
import geopandas as gpd

In [15]:
# Check current CRS
grid = gpd.read_file("C:/Users/Giorgos/Desktop/HMMY/10ο Εξάμηνο/Διπλωματική/2. Datasets/ELSTAT/ΔΗΜΟΤΙΚΕΣ ΚΟΙΝΟΤΗΤΕΣ - shapefiles/grid/magnesia-grid.shp")
print("Original CRS:", grid.crs)

Original CRS: EPSG:2100

In [16]:
# Reproject to WGS 84 (EPSG:4326)
grid = grid.to_crs(epsg=4326)

In [17]:
# Compute centroids
grid['centroid_lon'] = grid.geometry.centroid.x
grid['centroid_lat'] = grid.geometry.centroid.y

# Save to CSV
grid.to_csv("grids2.csv", index=False)

C:\Users\Giorgos\AppData\Local\Temp\ipykernel_19920\2168233096.py:2: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  grid['centroid_lon'] = grid.geometry.centroid.x
C:\Users\Giorgos\AppData\Local\Temp\ipykernel_19920\2168233096.py:3: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  grid['centroid_lat'] = grid.geometry.centroid.y

In [18]:
# Load the CSV
df = pd.read_csv("grids2.csv")

In [19]:
df.head()

,id,left,top,right,bottom,row_index,col_index,centroi_lo,centroi_la,geometry,centroid_lon,centroid_lat
0,1.0,369341.6791,4.383963e+06,369841.6791,4.383463e+06,0.0,0.0,3695.0000,4383712.906,POLYGON ((22.479991203666504 39.59805048281335...,22.482951,39.595837
1,2.0,369341.6791,4.383463e+06,369841.6791,4.382963e+06,1.0,0.0,369591.6791,4383212.906,POLYGON ((22.480089649443066 39.59354688377664...,22.483049,39.591333
2,3.0,369341.6791,4.382963e+06,369841.6791,4.382463e+06,2.0,0.0,369591.6791,4382712.906,POLYGON ((22.48018807311691 39.589043281018085...,22.483148,39.586829
3,4.0,369341.6791,4.382463e+06,369841.6791,4.381963e+06,3.0,0.0,369591.6791,4382212.906,POLYGON ((22.480286474693532 39.58453967453788...,22.483246,39.582326
4,5.0,369341.6791,4.381963e+06,369841.6791,4.381463e+06,4.0,0.0,369591.6791,4381712.906,POLYGON ((22.480384854178418 39.58003606433615...,22.483344,39.577822

In [20]:
# Create base map centered around Magnesia
m = folium.Map(location=[df['centroid_lat'].mean(), df['centroid_lon'].mean()], zoom_start=11)

# Add each grid centroid as a marker or circle
for _, row in df.iterrows():
    folium.CircleMarker(
        location=[row['centroid_lat'], row['centroid_lon']],
        radius=0.5,
        color='blue',
        fill=True,
        fill_opacity=0.6
    ).add_to(m)

In [21]:
# Save and display
m.save("magnesia_grid_centroids.html")

In [3]:
# Load the CSV
df = pd.read_csv("grids.csv")
df.head()

,id,left,top,right,bottom,row_index,col_index,centroi_lo,centroi_la,geometry,centroid_lon,centroid_lat
0,1.0,369341.6791,4.383963e+06,369841.6791,4.383463e+06,0.0,0.0,3695.0000,4383712.906,POLYGON ((22.479991203666504 39.59805048281335...,22.482951,39.595837
1,2.0,369341.6791,4.383463e+06,369841.6791,4.382963e+06,1.0,0.0,369591.6791,4383212.906,POLYGON ((22.480089649443066 39.59354688377664...,22.483049,39.591333
2,3.0,369341.6791,4.382963e+06,369841.6791,4.382463e+06,2.0,0.0,369591.6791,4382712.906,POLYGON ((22.48018807311691 39.589043281018085...,22.483148,39.586829
3,4.0,369341.6791,4.382463e+06,369841.6791,4.381963e+06,3.0,0.0,369591.6791,4382212.906,POLYGON ((22.480286474693532 39.58453967453788...,22.483246,39.582326
4,5.0,369341.6791,4.381963e+06,369841.6791,4.381463e+06,4.0,0.0,369591.6791,4381712.906,POLYGON ((22.480384854178418 39.58003606433615...,22.483344,39.577822

In [22]:
df.drop(columns=['centroi_lo', 'centroi_la'], inplace=True)

In [23]:
df.rename(columns={'centroid_lon': 'centroid_longitude', 'centroid_lat': 'centroid_latitude'}, inplace=True)

In [24]:
df.head()

,id,left,top,right,bottom,row_index,col_index,geometry,centroid_longitude,centroid_latitude
0,1.0,369341.6791,4.383963e+06,369841.6791,4.383463e+06,0.0,0.0,POLYGON ((22.479991203666504 39.59805048281335...,22.482951,39.595837
1,2.0,369341.6791,4.383463e+06,369841.6791,4.382963e+06,1.0,0.0,POLYGON ((22.480089649443066 39.59354688377664...,22.483049,39.591333
2,3.0,369341.6791,4.382963e+06,369841.6791,4.382463e+06,2.0,0.0,POLYGON ((22.48018807311691 39.589043281018085...,22.483148,39.586829
3,4.0,369341.6791,4.382463e+06,369841.6791,4.381963e+06,3.0,0.0,POLYGON ((22.480286474693532 39.58453967453788...,22.483246,39.582326
4,5.0,369341.6791,4.381963e+06,369841.6791,4.381463e+06,4.0,0.0,POLYGON ((22.480384854178418 39.58003606433615...,22.483344,39.577822

In [25]:
df.to_csv("grids.csv", index=False)